/// Countries & Languages reference data for registration filters
class RefCountries {
  static const List<Map<String, String>> countries = [
    {'code': 'AL', 'name': 'Albania'},
    {'code': 'AD', 'name': 'Andorra'},
    {'code': 'AM', 'name': 'Armenia'},
    {'code': 'AT', 'name': 'Austria'},
    {'code': 'AZ', 'name': 'Azerbaijan'},
    {'code': 'BY', 'name': 'Belarus'},
    {'code': 'BE', 'name': 'Belgium'},
    {'code': 'BA', 'name': 'Bosnia and Herzegovina'},
    {'code': 'BR', 'name': 'Brazil'},
    {'code': 'BG', 'name': 'Bulgaria'},
    {'code': 'CA', 'name': 'Canada'},
    {'code': 'CL', 'name': 'Chile'},
    {'code': 'CN', 'name': 'China'},
    {'code': 'CO', 'name': 'Colombia'},
    {'code': 'HR', 'name': 'Croatia'},
    {'code': 'CW', 'name': 'Curaçao'},
    {'code': 'CY', 'name': 'Cyprus'},
    {'code': 'CZ', 'name': 'Czech Republic'},
    {'code': 'DK', 'name': 'Denmark'},
    {'code': 'EE', 'name': 'Estonia'},
    {'code': 'FI', 'name': 'Finland'},
    {'code': 'FR', 'name': 'France'},
    {'code': 'GE', 'name': 'Georgia'},
    {'code': 'DE', 'name': 'Germany'},
    {'code': 'GI', 'name': 'Gibraltar'},
    {'code': 'GR', 'name': 'Greece'},
    {'code': 'HU', 'name': 'Hungary'},
    {'code': 'IS', 'name': 'Iceland'},
    {'code': 'IN', 'name': 'India'},
    {'code': 'ID', 'name': 'Indonesia'},
    {'code': 'IE', 'name': 'Ireland'},
    {'code': 'IM', 'name': 'Isle of Man'},
    {'code': 'IL', 'name': 'Israel'},
    {'code': 'IT', 'name': 'Italy'},
    {'code': 'JP', 'name': 'Japan'},
    {'code': 'KZ', 'name': 'Kazakhstan'},
    {'code': 'KE', 'name': 'Kenya'},
    {'code': 'XK', 'name': 'Kosovo'},
    {'code': 'KG', 'name': 'Kyrgyzstan'},
    {'code': 'LV', 'name': 'Latvia'},
    {'code': 'LT', 'name': 'Lithuania'},
    {'code': 'LU', 'name': 'Luxembourg'},
    {'code': 'MY', 'name': 'Malaysia'},
    {'code': 'MT', 'name': 'Malta'},
    {'code': 'MX', 'name': 'Mexico'},
    {'code': 'MD', 'name': 'Moldova'},
    {'code': 'ME', 'name': 'Montenegro'},
    {'code': 'NL', 'name': 'Netherlands'},
    {'code': 'NZ', 'name': 'New Zealand'},
    {'code': 'NG', 'name': 'Nigeria'},
    {'code': 'MK', 'name': 'North Macedonia'},
    {'code': 'NO', 'name': 'Norway'},
    {'code': 'PE', 'name': 'Peru'},
    {'code': 'PH', 'name': 'Philippines'},
    {'code': 'PL', 'name': 'Poland'},
    {'code': 'PT', 'name': 'Portugal'},
    {'code': 'RO', 'name': 'Romania'},
    {'code': 'RU', 'name': 'Russia'},
    {'code': 'RS', 'name': 'Serbia'},
    {'code': 'SG', 'name': 'Singapore'},
    {'code': 'SK', 'name': 'Slovakia'},
    {'code': 'SI', 'name': 'Slovenia'},
    {'code': 'ZA', 'name': 'South Africa'},
    {'code': 'KR', 'name': 'South Korea'},
    {'code': 'ES', 'name': 'Spain'},
    {'code': 'SE', 'name': 'Sweden'},
    {'code': 'CH', 'name': 'Switzerland'},
    {'code': 'TJ', 'name': 'Tajikistan'},
    {'code': 'TH', 'name': 'Thailand'},
    {'code': 'TR', 'name': 'Turkey'},
    {'code': 'UA', 'name': 'Ukraine'},
    {'code': 'AE', 'name': 'United Arab Emirates'},
    {'code': 'GB', 'name': 'United Kingdom'},
    {'code': 'US', 'name': 'United States'},
    {'code': 'UZ', 'name': 'Uzbekistan'},
    {'code': 'VN', 'name': 'Vietnam'},
  ];

  static const List<Map<String, String>> languages = [
    {'code': 'en', 'name': 'English'},
    {'code': 'de', 'name': 'German'},
    {'code': 'pl', 'name': 'Polish'},
    {'code': 'ru', 'name': 'Russian'},
    {'code': 'uk', 'name': 'Ukrainian'},
    {'code': 'fr', 'name': 'French'},
    {'code': 'es', 'name': 'Spanish'},
    {'code': 'pt', 'name': 'Portuguese'},
    {'code': 'it', 'name': 'Italian'},
    {'code': 'nl', 'name': 'Dutch'},
    {'code': 'sv', 'name': 'Swedish'},
    {'code': 'da', 'name': 'Danish'},
    {'code': 'no', 'name': 'Norwegian'},
    {'code': 'fi', 'name': 'Finnish'},
    {'code': 'el', 'name': 'Greek'},
    {'code': 'cs', 'name': 'Czech'},
    {'code': 'ro', 'name': 'Romanian'},
    {'code': 'bg', 'name': 'Bulgarian'},
    {'code': 'hr', 'name': 'Croatian'},
    {'code': 'sr', 'name': 'Serbian'},
    {'code': 'hu', 'name': 'Hungarian'},
    {'code': 'tr', 'name': 'Turkish'},
    {'code': 'ja', 'name': 'Japanese'},
    {'code': 'ko', 'name': 'Korean'},
    {'code': 'zh', 'name': 'Chinese'},
    {'code': 'ar', 'name': 'Arabic'},
    {'code': 'hi', 'name': 'Hindi'},
    {'code': 'th', 'name': 'Thai'},
    {'code': 'ka', 'name': 'Georgian'},
    {'code': 'he', 'name': 'Hebrew'},
    {'code': 'vi', 'name': 'Vietnamese'},
  ];

  static List<String> countryNames() => countries.map((c) => c['name']!).toList();
  static List<String> languageNames() => languages.map((l) => l['name']!).toList();
  static String? languageCode(String name) => languages.firstWhere((l) => l['name'] == name, orElse: () => {})['code'];
  static String? languageName(String code) => languages.firstWhere((l) => l['code'] == code, orElse: () => {})['name'];
}
