/// GURO JOBS Localization
class AppStrings {
  static String _currentLang = 'en';

  static String get currentLang => _currentLang;

  static void setLang(String lang) {
    _currentLang = lang;
  }

  static final Map<String, Map<String, String>> _strings = {
    'en': {
      'app_name': 'GURO JOBS',
      'get_started': 'Get Started',
      'already_have_account': 'Already have an account? Sign In',
      'home': 'Home',
      'jobs': 'Jobs',
      'applications': 'Applications',
      'profile': 'Profile',
      'hello': 'Hello',
      'find_dream_job': 'Find your dream iGaming job',
      'search_jobs': 'Search jobs, companies...',
      'jobs_available': 'Jobs Available',
      'profile_views': 'Profile Views',
      'saved': 'Saved',
      'interviews': 'Interviews',
      'popular_categories': 'Popular Categories',
      'recent_jobs': 'Recent Jobs',
      'see_all': 'See All',
      'find_jobs': 'Find Jobs',
      'search_by_title': 'Search by title, skill...',
      'all': 'All',
      'remote': 'Remote',
      'full_time': 'Full-time',
      'senior': 'Senior',
      'my_applications': 'My Applications',
      'track_applications': 'Track your job applications',
      'no_applications': 'No Applications Yet',
      'start_applying': 'Start applying to jobs and track\nyour progress here',
      'browse_jobs': 'Browse Jobs',
      'candidate': 'Candidate',
      'employer': 'Employer',
      'admin': 'Admin',
      'select_role': 'I am a...',
      'complete_profile': 'Complete Your Profile',
      'complete_profile_desc': 'Add skills, experience and CV to get noticed',
      'edit_profile': 'Edit Profile',
      'my_cv': 'My CV / Resume',
      'saved_jobs': 'Saved Jobs',
      'notifications': 'Notifications',
      'settings': 'Settings',
      'help_support': 'Help & Support',
      'help': 'Help',
      'language': 'Language',
      'dark_mode': 'Dark Mode',
      'dark_mode_desc': 'Switch to dark theme',
      'push_notifications': 'Push Notifications',
      'push_notifications_desc': 'Get notified about new jobs',
      'email_notifications': 'Email Notifications',
      'email_notifications_desc': 'Receive job alerts via email',
      'appearance': 'Appearance',
      'account': 'Account',
      'change_password': 'Change Password',
      'clear_app_data': 'Clear App Data',
      'clear_app_data_confirm': 'This will log you out and clear all saved preferences. Continue?',
      'clear': 'Clear',
      'delete_account': 'Delete Account',
      'delete_account_confirm': 'This action is permanent and cannot be undone. All your data will be deleted.',
      'delete': 'Delete',
      'location': 'Location',
      'logout': 'Logout',
      'logout_confirm': 'Are you sure you want to logout?',
      'cancel': 'Cancel',
      'join_community': 'Join Our Community',
      'join_community_desc': 'Connect with iGaming professionals',
      'welcome_back': 'Welcome Back',
      'create_account': 'Create Account',
      'sign_in_subtitle': 'Sign in to find your next iGaming role',
      'register_subtitle': 'Join GURO JOBS and start your iGaming career',
      'register': 'Register',
      'sign_in': 'Sign In',
      'full_name': 'Full Name',
      'email_address': 'Email Address',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'no_account': "Don't have an account? ",
      'have_account': 'Already have an account? ',
      'forgot_password': 'Forgot Password?',
      'forgot_password_title': 'Reset Password',
      'forgot_password_desc': 'Enter your email and we\'ll send you a reset link',
      'send_reset_link': 'Send Reset Link',
      'reset_sent': 'Password reset link sent to your email',
      'back_to_login': 'Back to Sign In',
      'terms_privacy': 'Terms & Privacy',
      'terms_read': 'Please read and accept our terms before continuing',
      'scroll_hint': 'Scroll down to read all terms',
      'agree_terms': 'I have read and agree to the Terms of Service and Privacy Policy',
      'accept_continue': 'Accept & Continue',
      'igaming_platform': 'Your Gateway to the World\'s Most Profitable Verticals',
      'gambling': 'Gambling',
      'betting': 'Betting',
      'crypto': 'Crypto',
      'nutra': 'Nutra',
      'dating': 'Dating',
      'ecommerce': 'E-commerce',
      'fintech': 'FinTech',
      'other': 'Other',
      'connection_error': 'Connection error. Please try again.',
      'invalid_credentials': 'Invalid credentials',
      'enter_name': 'Please enter your name',
      'enter_email': 'Please enter your email',
      'valid_email': 'Please enter a valid email',
      'enter_password': 'Please enter a password',
      'password_min': 'Password must be at least 8 characters',
      'passwords_mismatch': 'Passwords do not match',
      'phone': 'Phone',
      'telegram': 'Telegram',
      'or': 'or',
      'name_hint': 'John Doe',
      'email_hint': 'your@email.com',
      'password_hint': 'Min 8 characters',
      'confirm_hint': 'Repeat password',
      'phone_hint': '+48 000 000 000',
      'telegram_hint': '@username',
      // Connections screen
      'connections': 'Connections',
      'messengers': 'Messengers',
      'messengers_desc': 'Connect messengers to receive job alerts and communicate with employers',
      'social_networks': 'Social Networks',
      'social_desc': 'Link your social profiles to boost visibility to employers',
      'connected': 'Connected',
      'disconnected': 'disconnected',
      'connect': 'Connect',
      'connect_title': 'Connect',
      'connect_scan_desc': 'Scan QR code or tap connect to link your',
      'scan_to_connect': 'Scan to connect',
      'connected_success': 'connected successfully!',
      'telegram_name': 'Telegram',
      'telegram_desc': 'Get instant job notifications via Telegram bot',
      'whatsapp_name': 'WhatsApp',
      'whatsapp_desc': 'Receive job alerts and employer messages',
      'viber_name': 'Viber',
      'viber_desc': 'Connect for quick employer communication',
      'email_name': 'Email',
      'email_desc': 'Receive job offers and updates via email',
      'signal_name': 'Signal',
      'signal_desc': 'Secure messaging with employers',
      'linkedin_name': 'LinkedIn',
      'linkedin_desc': 'Import your professional profile and connections',
      'github_name': 'GitHub',
      'github_desc': 'Showcase your technical portfolio',
      'twitter_name': 'X (Twitter)',
      'twitter_desc': 'Follow iGaming companies and job postings',
      'facebook_name': 'Facebook',
      'facebook_desc': 'Connect with iGaming community groups',
      'instagram_name': 'Instagram',
      'instagram_desc': 'Share your professional journey',
      'discord_name': 'Discord',
      'discord_desc': 'Join iGaming community servers',
      // Billing screen
      'billing_plans': 'Billing & Plans',
      'choose_plan': 'Choose Your Plan',
      'choose_plan_desc': 'Unlock premium features and boost your job search',
      'trial_active': 'Free Trial Active',
      'trial_expired': 'Trial Expired',
      'trial_remaining': 'Time remaining to choose a plan:',
      'trial_upgrade': 'Upgrade now to continue using premium features',
      'plan_basic': 'Basic',
      'plan_premium': 'Premium',
      'plan_vip': 'VIP',
      'popular': 'POPULAR',
      'per_month': '/month',
      'days': 'days',
      'plan_basic_contacts': 'Up to 10 candidate contacts per day',
      'plan_basic_desc': 'View candidate profiles and open contacts',
      'plan_premium_contacts': 'Up to 50 candidate contacts per day for the whole team',
      'plan_premium_team': 'Team access: up to 3 users',
      'plan_premium_linkedin': 'LinkedIn profiles of candidates',
      'plan_premium_desc': 'Connect team members to share plan benefits',
      'plan_vip_contacts': 'Unlimited candidate contacts',
      'plan_vip_team': 'Team access: up to 5 users',
      'plan_vip_bot': 'Telegram bot: auto-alerts for new resumes matching your vacancies',
      'plan_vip_desc': 'Real-time candidate search with instant notifications',
      'feat_email_alerts': 'Email job alerts',
      'feat_priority_search': 'Priority in search results',
      'feat_cv_analytics': 'CV analytics & insights',
      'payment_method': 'Payment Method',
      'payment_providers': 'Payment Providers',
      'pay_card': 'Credit / Debit Card',
      'pay_card_desc': 'Visa, Mastercard, Amex',
      'pay_crypto': 'Cryptocurrency',
      'pay_crypto_desc': 'BTC, ETH, USDT, SOL',
      'pay_trustly': 'Trustly',
      'pay_trustly_desc': 'Direct bank transfer, fast & secure',
      'pay_skrill': 'Skrill',
      'pay_skrill_desc': 'E-wallet payments, instant',
      'pay_neteller': 'Neteller',
      'pay_neteller_desc': 'Digital wallet, low fees',
      'pay_paysafecard': 'Paysafecard',
      'pay_paysafecard_desc': 'Prepaid card, anonymous',
      'pay_stripe_desc': 'Cards, Apple Pay, Google Pay',
      'pay_paypal_desc': 'PayPal account, fast & secure',
      'pay_revolut_desc': 'Revolut account, instant transfer',
      'redirect_paypal': 'You will be redirected to PayPal to authorize the payment securely.',
      'redirect_revolut': 'You will be redirected to Revolut to authorize the payment instantly.',
      'stripe_secure': 'Powered by Stripe — PCI DSS Level 1 certified',
      'step_stripe_connect': 'Connecting to Stripe...',
      'step_paypal_connect': 'Connecting to PayPal...',
      'step_revolut_connect': 'Connecting to Revolut...',
      'subscribe_now': 'Subscribe Now',
      'select_plan_continue': 'Select a plan to continue',
      'confirm_subscription': 'Confirm Subscription',
      'subscribe_to': 'Subscribe to',
      'plan_via': 'plan via',
      'subscribe': 'Subscribe',
      'subscribed_to': 'Subscribed to',
      'payment_processing': 'Payment processing...',
      'remind_later': 'Remind me later',
      'left': 'left',
      'free_trial': 'Free trial:',
      'remaining': 'remaining',
      // Payment flow
      'confirm_order': 'Confirm Order',
      'what_you_get': 'What you get',
      'continue_to_payment': 'Continue to Payment',
      'amount_to_pay': 'Amount to pay',
      'pay': 'Pay',
      'secure_payment': 'Secured with 256-bit SSL encryption',
      'card_details': 'Card Details',
      'cardholder_name': 'Cardholder Name',
      'card_number': 'Card Number',
      'invalid_card': 'Enter valid card number',
      'invalid_expiry': 'Enter MM/YY',
      'invalid_cvv': 'Enter CVV',
      'select_crypto': 'Select Cryptocurrency',
      'crypto_note': 'After clicking Pay you will receive a wallet address. Send the exact amount within 30 minutes.',
      'redirect_bank': 'You will be redirected to your bank to authorize the payment securely.',
      'enter_pin': 'Enter 16-digit PIN code',
      'invalid_pin': 'Enter valid 16-digit PIN',
      'paysafecard_note': 'Enter the 16-digit PIN from your Paysafecard voucher.',
      'field_required': 'This field is required',
      'processing_payment': 'Processing Payment',
      'do_not_close': 'Please do not close this screen',
      'step_verifying_card': 'Verifying card details...',
      'step_contacting_bank': 'Contacting your bank...',
      'step_processing_payment': 'Processing payment...',
      'step_confirming': 'Confirming subscription...',
      'step_generating_address': 'Generating wallet address...',
      'step_waiting_confirmation': 'Waiting for blockchain confirmation...',
      'step_connecting_bank': 'Connecting to bank...',
      'step_authorizing': 'Authorizing payment...',
      'step_verifying_pin': 'Verifying PIN code...',
      'step_connecting_wallet': 'Connecting to wallet...',
      'payment_successful': 'Payment Successful!',
      'welcome_to_plan': 'Welcome to {plan}! Your subscription is now active.',
      'plan': 'Plan',
      'amount_paid': 'Amount Paid',
      'billing_period': 'Billing Period',
      'monthly': 'Monthly',
      'next_payment': 'Next Payment',
      'receipt_sent': 'Receipt sent to your email',
      'your_benefits': 'Your Benefits',
      'start_using': 'Start Using GURO JOBS',
      'no_jobs_found': 'No jobs found',
      'try_different_filters': 'Try different filters',
      'jobs_suffix': 'Jobs',
      // Chat screen
      'chat': 'Chat',
      'chats': 'Chats',
      'all_channels': 'All',
      'no_chats': 'No conversations yet',
      'no_chats_desc': 'Connect messengers and start chatting with employers',
      'type_message': 'Type a message...',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'online': 'Online',
      'offline': 'Offline',
      'typing': 'typing...',
      'sent': 'Sent',
      'delivered': 'Delivered',
      'read': 'Read',
      'via': 'via',
      'employer_chat': 'Employer',
      'agency_chat': 'Agency',
      'support_chat': 'Support',
      'unread_messages': 'unread',
      'search_chats': 'Search conversations...',
      'attachment': 'Attachment',
      'photo': 'Photo',
      'document': 'Document',
      'reply': 'Reply',
      'start_conversation': 'Start Conversation',
      // CV
      'cv_uploaded': 'CV uploaded successfully!',
      'cv_removed': 'CV removed',
      'cv_slots': 'CV uploaded',
      'select_cv_categories': 'Select Categories',
      'select_cv_categories_desc': 'Choose verticals for this CV (you can select multiple)',
      'upload_cv': 'Upload CV',
      'upload_another_cv': 'Upload Another CV',
      'upload_cv_desc': 'Upload your resume to apply\nfor jobs faster',
      'upload_cv_formats': 'PDF, DOC, DOCX (max 5MB)',
      'upload_cv_max': 'You can upload up to 2 CVs',
      'upload_cv_hint': 'For a different vertical or position',
      'uploading': 'Uploading...',
      'choose_file': 'Choose File',
      'uploaded': 'Uploaded',
      'replace': 'Replace',
      'remove': 'Remove',
      // Workspace
      'workspace': 'Workspace',
      'notes': 'Notes',
      'notes_desc': 'Quick notes and ideas',
      'drafts': 'Drafts',
      'drafts_desc': 'Saved application drafts',
      'integrations': 'Integrations',
      'notion_connect': 'Notion',
      'notion_desc': 'Sync notes and job tracking boards',
      'obsidian_connect': 'Obsidian',
      'obsidian_desc': 'Export notes to your Obsidian vault',
      'gdrive_connect': 'Google Drive',
      'gdrive_desc': 'Store and sync your CV files in the cloud',
      'gsheets_connect': 'Google Sheets',
      'gsheets_desc': 'Track job applications in a spreadsheet',
      'new_note': 'New Note',
      'new_draft': 'New Draft',
      'note_placeholder': 'Start writing...',
      'save': 'Save',
      'no_notes': 'No notes yet',
      'no_notes_desc': 'Tap + to create your first note',
      'no_drafts': 'No drafts yet',
      'no_drafts_desc': 'Draft applications will appear here',
      'coming_soon': 'Coming Soon',
      'integration_soon': 'Integration will be available soon',
      // CV Builder
      'create_cv': 'Create CV',
      'create_cv_desc': 'Build your professional resume',
      'cv_builder': 'CV Builder',
      'desired_position': 'Desired Position',
      'desired_position_hint': 'e.g. Flutter Developer',
      'about_me': 'About Me',
      'about_me_hint': 'Brief description of yourself...',
      'skills': 'Skills',
      'skills_hint': 'e.g. Flutter, Dart, React...',
      'add_skill': 'Add',
      'work_experience': 'Work Experience',
      'company_name': 'Company',
      'position_title': 'Position',
      'period': 'Period',
      'period_hint': 'e.g. 2024 - Present',
      'description': 'Description',
      'description_hint': 'What did you do?',
      'add_experience': 'Add Experience',
      'education': 'Education',
      'institution': 'Institution',
      'degree': 'Degree / Program',
      'add_education': 'Add Education',
      'contact_info': 'Contact Info',
      'contacts': 'Contacts',
      'contacts_hidden': 'Contacts are hidden',
      'reveal_contact': 'Open Contact',
      'reveal_contact_confirm': 'Reveal this candidate\'s contacts?',
      'reveal_contact_cost': 'This will use 1 of your daily contact credits',
      'contact_revealed': 'Contact revealed!',
      'no_credits_left': 'No credits left today',
      'no_credits_desc': 'You have used all daily contact reveals. Upgrade your plan for more.',
      'credits_remaining': 'credits remaining today',
      'daily_limit': 'Daily limit',
      'upgrade_plan': 'Upgrade Plan',
      'contact_email': 'Email',
      'contact_telegram': 'Telegram',
      'contact_phone': 'Phone',
      'contact_all': 'All contacts',
      'already_unlocked': 'Already revealed',
      'salary_expectation': 'Salary Expectation',
      'salary_hint': 'e.g. \$5,000',
      'preferred_geo': 'Preferred Location',
      'country_hint': 'Enter country, e.g. USA, Canada...',
      'add_messenger': 'Add Messenger',
      'messenger_name_hint': 'e.g. Viber, Signal, Discord...',
      'generate_cv': 'Generate CV',
      'cv_created': 'CV created successfully!',
      'section_required': 'Please fill in required fields',
      // Organizer
      'organizer': 'Organizer',
      'total': 'Total',
      'interviews': 'Interviews',
      'offers': 'Offers',
      'status_sent': 'Sent',
      'status_viewed': 'Viewed',
      'status_interview': 'Interview',
      'status_offer': 'Offer',
      'status_rejected': 'Rejected',
      'applied': 'Applied',
      'timeline': 'Timeline',
      'meetings': 'Meetings',
      'add_meeting': 'Add Meeting',
      'meeting_type': 'Type',
      'meeting_date': 'Date',
      'meeting_time': 'Time',
      'meeting_link': 'Link',
      'meeting_video': 'Video Call',
      'meeting_phone': 'Phone',
      'meeting_onsite': 'On-site',
      'add_note': 'Add Note',
      'note_hint': 'Write a note...',
      'no_meetings': 'No meetings scheduled',
      'no_notes_app': 'No notes yet',
      'delete': 'Delete',
      'edit': 'Edit',
      'done': 'Done',
      'schedule_meeting': 'Schedule Meeting',
      'details': 'Details',
      'status_change': 'Status changed to',
      'application_sent': 'Application sent',
      'cv_viewed': 'CV was viewed',
      'interview_scheduled': 'Interview scheduled',
      'offer_received': 'Offer received',
      'rejected_info': 'Application rejected',
      'open_link': 'Open Link',
      'filters': 'Filters',
      'salary': 'Salary',
      'salary_range': 'Salary Range',
      'from': 'From',
      'to': 'To',
      'experience': 'Experience',
      'no_experience': 'No Experience',
      'year_1': '1 year',
      'years_2': '2 years',
      'years_3': '3 years',
      'years_4': '4 years',
      'years_5': '5 years',
      'years_6': '6 years',
      'years_7': '7 years',
      'years_8': '8 years',
      'years_9': '9 years',
      'years_10_plus': '10+ years',
      'work_setup': 'Work Setup',
      'office': 'Office',
      'hybrid': 'Hybrid',
      'verticals': 'Verticals',
      'english_level': 'English',
      'no_english': 'No English',
      'beginner': 'Beginner/Elementary',
      'pre_intermediate': 'Pre-Intermediate',
      'intermediate': 'Intermediate',
      'upper_intermediate': 'Upper-Intermediate',
      'advanced': 'Advanced/Fluent',
      'proficient': 'Proficient',
      'native_speaker': 'Native Speaker',
      'geo': 'Geo',
      'worldwide': 'Worldwide',
      'eu_countries': 'EU Countries',
      'other_countries': 'Other Countries',
      'hide_with_replies': 'Do not show vacancies with replies/offers',
      'show_salary_range': 'Show jobs with salary ranges',
      'apply_filters': 'Apply Filters',
      'reset_filters': 'Reset',
      'filters_applied': 'Filters applied',
      // Employer
      'emp_welcome': 'Manage your job listings',
      'emp_my_jobs': 'My Jobs',
      'emp_candidates': 'Candidates',
      'emp_company': 'Company',
      'emp_active_jobs': 'Active Jobs',
      'emp_total_apps': 'Applications',
      'emp_new_today': 'New Today',
      'emp_job_views': 'Job Views',
      'emp_hired': 'Hired',
      'emp_quick_actions': 'Quick Actions',
      'emp_post_job': 'Post Job',
      'emp_search_talent': 'Search Talent',
      'emp_recent_apps': 'Recent Applications',
      'emp_status_active': 'Active',
      'emp_status_paused': 'Paused',
      'emp_status_closed': 'Closed',
      'emp_status_draft': 'Draft',
      'emp_no_jobs': 'No jobs found',
      'emp_no_candidates': 'No candidates found',
      'emp_all_positions': 'All Positions',
      'emp_cand_new': 'New',
      'emp_cand_reviewed': 'Reviewed',
      'emp_cand_interview': 'Interview',
      'emp_cand_hired': 'Hired',
      'emp_cand_rejected': 'Rejected',
      'emp_applied_for': 'Applied for',
      'emp_change_status': 'Change Status',
      'emp_write_msg': 'Write',
      'emp_view_cv': 'View CV',
      'emp_view_apps': 'View Apps',
      'emp_posted': 'Posted',
      'emp_post_new_job': 'Post New Job',
      'emp_job_title': 'Job Title',
      'emp_job_title_hint': 'e.g. Senior Affiliate Manager',
      'emp_vertical': 'Vertical',
      'emp_work_type': 'Work Type',
      'emp_job_desc_hint': 'Describe the role, requirements...',
      'emp_publish_job': 'Publish Job',
      'emp_job_created': 'Job posted successfully!',
      'emp_title_required': 'Job title is required',
      'preview_and_publish': 'Preview & Publish',
      'job_preview': 'Job Preview',
      'job_preview_note': 'This is how candidates will see your job listing. Check all details before publishing.',
      'requirements': 'Requirements',
      'requirements_hint': 'List job requirements (one per line)',
      'tags': 'Tags / Keywords',
      'tags_hint': 'flutter, dart, react (comma separated)',
      'publishing_job': 'Publishing Job...',
      'updating_job': 'Updating Job...',
      'step_validating_job': 'Validating job details...',
      'step_checking_plan': 'Checking your plan limits...',
      'step_publishing': 'Publishing to job board...',
      'step_indexing': 'Indexing for search...',
      'job_published': 'Job Published!',
      'job_updated': 'Job Updated!',
      'active': 'Active',
      'public': 'Public',
      'visibility': 'Visibility',
      'posted_at': 'Posted',
      'job_visible_note': 'Your job is now visible to thousands of iGaming professionals worldwide.',
      'what_happens_next': 'What happens next?',
      'next_candidates_see': 'Candidates will see your vacancy in search and job feed.',
      'next_applications': 'You will receive applications in the Candidates tab.',
      'next_review': 'Review candidates, reveal contacts, and hire the best!',
      'back_to_dashboard': 'Back to Dashboard',
      'emp_company_profile': 'Company Profile',
      'emp_subscription': 'Subscription & Billing',
      // Admin
      'adm_panel': 'Admin',
      'adm_welcome': 'Platform management panel',
      'adm_platform_stats': 'Platform Stats',
      'adm_total_users': 'Total Users',
      'adm_total_jobs': 'Total Jobs',
      'adm_companies': 'Companies',
      'adm_new_today': 'New Today',
      'adm_revenue': 'Revenue',
      'adm_payments': 'Payments',
      'adm_reports': 'Reports',
      'adm_quick_actions': 'Quick Actions',
      'adm_manage_users': 'Manage Users',
      'adm_moderate_jobs': 'Moderate Jobs',
      'adm_analytics': 'Analytics',
      'adm_pending_approvals': 'Pending Approvals',
      'adm_recent_activity': 'Recent Activity',
      'adm_users': 'Users',
      'adm_search_users': 'Search users by name or email...',
      'adm_candidates': 'Candidates',
      'adm_employers': 'Employers',
      'adm_admins': 'Admins',
      'adm_active': 'Active',
      'adm_pending': 'Pending',
      'adm_banned': 'Banned',
      'adm_no_users': 'No users found',
      'adm_registered': 'Registered',
      'adm_last_login': 'Last Login',
      'adm_jobs_applied': 'Jobs Applied',
      'adm_approve': 'Approve',
      'adm_reject': 'Reject',
      'adm_message': 'Message',
      'adm_ban': 'Ban',
      'adm_unban': 'Unban',
      'adm_job_moderation': 'Job Moderation',
      'adm_approved': 'Approved',
      'adm_rejected_status': 'Rejected',
      'adm_featured': 'Featured',
      'adm_security': 'Security',
      'adm_subscriptions': 'Subscriptions',
      'adm_subscribers': 'subscribers',
      'all': 'All',
      'expired': 'Expired',
      'cancelled': 'Cancelled',
      'change_plan': 'Change Plan',
      'extend': 'Extend',
      'extend_confirm': 'Extend subscription by:',
      'extended_by': 'extended by',
      'block': 'Block',
      'block_confirm': 'Block this company? Their subscription will be cancelled.',
      'blocked': 'blocked',
      'adm_approve_confirm': 'This user will get full access to the platform.',
      'adm_approved': 'approved',
      'adm_reject_reason': 'Please provide a reason for rejection:',
      'adm_reason_hint': 'Enter reason...',
      'adm_ban_confirm': 'This user will be banned from the platform.',
      'adm_unban_confirm': 'Restore access for this user?',
      'adm_unbanned': 'unbanned',
      'adm_approve_job_confirm': 'This job will be visible to all candidates.',
      'adm_reject_job_reason': 'Reason for rejecting this job listing:',
      'adm_feature_confirm': 'Feature this job at the top of search results?',
      'pending': 'Pending',
      'resolved': 'Resolved',
      'documents': 'Documents',
      'reason': 'Reason',
      'reported_by': 'Reported by',
      'adm_verify_approve': 'Verify this employer? They will receive a verified badge.',
      'adm_take_action': 'Take Action',
      'adm_warn_user': 'Send Warning',
      'adm_warning_sent': 'Warning sent',
      'adm_remove_content': 'Remove Content',
      'adm_content_removed': 'Content removed',
      'adm_dismiss': 'Dismiss',
      'adm_report_dismissed': 'Report dismissed',
      'adm_tools': 'ADMIN TOOLS',
      'adm_database': 'System & Database',
      'adm_verification': 'Verification',
      'adm_general': 'GENERAL',
      'what_is_it': 'What is it?',
      'key_roles': 'Key Roles',
      'industry_stats': 'Industry Stats',
      'skills_needed': 'Skills Needed',
      'want_to_learn': 'Want to learn more?',
      'guro_school_desc': 'Start your career in iGaming with professional courses at Guro School',
      'go_to_guro_school': 'Guro School',
      'admin_panel': 'Admin Panel',
      'admin_login_desc': 'Sign in with admin credentials',
      'admin_only_error': 'Access denied. Admin accounts only.',
      'find_job_or_hire': 'Find a Job or Hire Talent',
      'candidate_employer_desc': 'For candidates and employers',
      'choose_how_to_continue': 'Choose how to continue',
      // Jarvis
      'jarvis': 'Jarvis',
      'jarvis_hello': 'Hi! I\'m Jarvis, your AI assistant.',
      'jarvis_hint': 'Try: "Show today\'s stats" or "List active jobs"',
      'jarvis_ask': 'Ask Jarvis...',
      'jarvis_listening': 'Listening...',
      'jarvis_processing': 'Processing...',
      'jarvis_speaking': 'Speaking...',
      'jarvis_error': 'Error',
      'jarvis_connection_error': 'Connection error. Please try again.',
      // Filters
      'communication_preferences': 'Communication Preferences',
      'priority_language': 'Priority Language',
      'acceptable_languages': 'Acceptable Languages (1-3)',
      'select_language': 'Select language',
      'select_languages_hint': 'Tap to select languages',
      'candidate_filters': 'Country & Citizenship',
      'citizenship_country': 'Country of Citizenship',
      'select_country': 'Select country',
      'in_citizenship_country': 'Are you in your citizenship country?',
      'blocked_company_countries': 'Block Company Countries',
      'blocked_countries_hint': 'Countries where you don\'t want to work',
      'employer_filters': 'Candidate Preferences',
      'main_office_countries': 'Main Office Country',
      'select_countries': 'Select countries',
      'blocked_candidate_citizenships': 'Block Candidate Citizenships',
      'blocked_citizenships_hint': 'Citizenships you can\'t offer jobs to',
      'candidate_location_pref': 'Show Candidates',
      'all_candidates': 'All',
      'outside_citizenship': 'Outside their country',
      'save_changes': 'Save Changes',
      'profile_updated': 'Profile updated!',
    },
    'ru': {
      'app_name': 'GURO JOBS',
      'get_started': 'Начать',
      'already_have_account': 'Уже есть аккаунт? Войти',
      'home': 'Главная',
      'jobs': 'Вакансии',
      'applications': 'Отклики',
      'profile': 'Профиль',
      'hello': 'Привет',
      'find_dream_job': 'Найди работу мечты в iGaming',
      'search_jobs': 'Поиск вакансий, компаний...',
      'jobs_available': 'Вакансий',
      'profile_views': 'Просмотры',
      'saved': 'Сохранённые',
      'interviews': 'Собеседования',
      'popular_categories': 'Популярные категории',
      'recent_jobs': 'Новые вакансии',
      'see_all': 'Все',
      'find_jobs': 'Поиск вакансий',
      'search_by_title': 'Поиск по названию, навыку...',
      'all': 'Все',
      'remote': 'Удалённо',
      'full_time': 'Полная',
      'senior': 'Senior',
      'my_applications': 'Мои отклики',
      'track_applications': 'Отслеживай свои заявки',
      'no_applications': 'Откликов пока нет',
      'start_applying': 'Откликайся на вакансии и\nотслеживай прогресс здесь',
      'browse_jobs': 'Смотреть вакансии',
      'candidate': 'Кандидат',
      'employer': 'Работодатель',
      'admin': 'Админ',
      'select_role': 'Я...',
      'complete_profile': 'Заполни профиль',
      'complete_profile_desc': 'Добавь навыки, опыт и CV чтобы тебя заметили',
      'edit_profile': 'Редактировать профиль',
      'my_cv': 'Моё CV / Резюме',
      'saved_jobs': 'Сохранённые',
      'notifications': 'Уведомления',
      'settings': 'Настройки',
      'help_support': 'Помощь',
      'help': 'Помощь',
      'language': 'Язык',
      'dark_mode': 'Тёмная тема',
      'dark_mode_desc': 'Переключить на тёмную тему',
      'push_notifications': 'Push уведомления',
      'push_notifications_desc': 'Уведомления о новых вакансиях',
      'email_notifications': 'Email уведомления',
      'email_notifications_desc': 'Получать вакансии по email',
      'appearance': 'Внешний вид',
      'account': 'Аккаунт',
      'change_password': 'Изменить пароль',
      'clear_app_data': 'Очистить данные',
      'clear_app_data_confirm': 'Вы выйдете из аккаунта и все настройки будут сброшены. Продолжить?',
      'clear': 'Очистить',
      'delete_account': 'Удалить аккаунт',
      'delete_account_confirm': 'Это действие необратимо. Все ваши данные будут удалены.',
      'delete': 'Удалить',
      'location': 'Локация',
      'logout': 'Выйти',
      'logout_confirm': 'Вы уверены что хотите выйти?',
      'cancel': 'Отмена',
      'join_community': 'Вступить в комьюнити',
      'join_community_desc': 'Общайся с iGaming профессионалами',
      'welcome_back': 'С возвращением',
      'create_account': 'Создать аккаунт',
      'sign_in_subtitle': 'Войди чтобы найти работу в iGaming',
      'register_subtitle': 'Присоединяйся к GURO JOBS',
      'register': 'Регистрация',
      'sign_in': 'Войти',
      'full_name': 'Полное имя',
      'email_address': 'Email',
      'password': 'Пароль',
      'confirm_password': 'Повтори пароль',
      'no_account': 'Нет аккаунта? ',
      'have_account': 'Уже есть аккаунт? ',
      'forgot_password': 'Забыли пароль?',
      'forgot_password_title': 'Сброс пароля',
      'forgot_password_desc': 'Введите email и мы отправим ссылку для сброса',
      'send_reset_link': 'Отправить ссылку',
      'reset_sent': 'Ссылка для сброса отправлена на ваш email',
      'back_to_login': 'Назад к входу',
      'terms_privacy': 'Условия и политика',
      'terms_read': 'Прочитайте и примите условия перед продолжением',
      'scroll_hint': 'Прокрутите вниз чтобы прочитать',
      'agree_terms': 'Я прочитал и согласен с Условиями использования и Политикой конфиденциальности',
      'accept_continue': 'Принять и продолжить',
      'igaming_platform': 'Работа в самых прибыльных вертикалях мира',
      'gambling': 'Гемблинг',
      'betting': 'Беттинг',
      'crypto': 'Крипта',
      'nutra': 'Нутра',
      'dating': 'Дейтинг',
      'ecommerce': 'E-commerce',
      'fintech': 'FinTech',
      'other': 'Другое',
      'connection_error': 'Ошибка подключения. Попробуйте снова.',
      'invalid_credentials': 'Неверные данные',
      'enter_name': 'Введите имя',
      'enter_email': 'Введите email',
      'valid_email': 'Введите корректный email',
      'enter_password': 'Введите пароль',
      'password_min': 'Минимум 8 символов',
      'passwords_mismatch': 'Пароли не совпадают',
      'phone': 'Телефон',
      'telegram': 'Телеграм',
      'or': 'или',
      'name_hint': 'Иван Иванов',
      'email_hint': 'ваш@email.com',
      'password_hint': 'Минимум 8 символов',
      'confirm_hint': 'Повтори пароль',
      'phone_hint': '+48 000 000 000',
      'telegram_hint': '@username',
      // Connections screen
      'connections': 'Подключения',
      'messengers': 'Мессенджеры',
      'messengers_desc': 'Подключи мессенджеры для получения уведомлений и общения с работодателями',
      'social_networks': 'Социальные сети',
      'social_desc': 'Привяжи соцсети чтобы повысить видимость для работодателей',
      'connected': 'Подключено',
      'disconnected': 'отключен',
      'connect': 'Подключить',
      'connect_title': 'Подключить',
      'connect_scan_desc': 'Отсканируй QR-код или нажми подключить для привязки',
      'scan_to_connect': 'Сканируй для подключения',
      'connected_success': 'успешно подключен!',
      'telegram_name': 'Telegram',
      'telegram_desc': 'Мгновенные уведомления о вакансиях через Telegram бот',
      'whatsapp_name': 'WhatsApp',
      'whatsapp_desc': 'Получай уведомления и сообщения от работодателей',
      'viber_name': 'Viber',
      'viber_desc': 'Быстрая связь с работодателями',
      'email_name': 'Email',
      'email_desc': 'Получай предложения о работе и обновления по email',
      'signal_name': 'Signal',
      'signal_desc': 'Безопасный обмен сообщениями с работодателями',
      'linkedin_name': 'LinkedIn',
      'linkedin_desc': 'Импортируй профессиональный профиль и контакты',
      'github_name': 'GitHub',
      'github_desc': 'Покажи своё техническое портфолио',
      'twitter_name': 'X (Twitter)',
      'twitter_desc': 'Следи за iGaming компаниями и вакансиями',
      'facebook_name': 'Facebook',
      'facebook_desc': 'Присоединяйся к iGaming сообществам',
      'instagram_name': 'Instagram',
      'instagram_desc': 'Делись профессиональным путём',
      'discord_name': 'Discord',
      'discord_desc': 'Вступай в iGaming серверы',
      // Billing screen
      'billing_plans': 'Тарифы и оплата',
      'choose_plan': 'Выбери свой тариф',
      'choose_plan_desc': 'Разблокируй премиум функции и ускорь поиск работы',
      'trial_active': 'Бесплатный период',
      'trial_expired': 'Пробный период истёк',
      'trial_remaining': 'Осталось времени для выбора тарифа:',
      'trial_upgrade': 'Обнови тариф чтобы продолжить использование премиум функций',
      'plan_basic': 'Базовый',
      'plan_premium': 'Премиум',
      'plan_vip': 'VIP',
      'popular': 'ПОПУЛЯРНЫЙ',
      'per_month': '/мес',
      'days': 'дней',
      'plan_basic_contacts': 'До 10 контактов кандидатов в сутки',
      'plan_basic_desc': 'Просмотр профилей и открытие контактов',
      'plan_premium_contacts': 'До 50 контактов на всю команду в сутки',
      'plan_premium_team': 'Командный доступ: до 3 пользователей',
      'plan_premium_linkedin': 'LinkedIn профили кандидатов',
      'plan_premium_desc': 'Подключите членов команды к вашему тарифу',
      'plan_vip_contacts': 'Неограниченное количество контактов',
      'plan_vip_team': 'Командный доступ: до 5 пользователей',
      'plan_vip_bot': 'Telegram бот: авто-оповещение о новых резюме по вашим вакансиям',
      'plan_vip_desc': 'Поиск кандидатов в реальном времени с мгновенными уведомлениями',
      'feat_email_alerts': 'Email уведомления о вакансиях',
      'feat_priority_search': 'Приоритет в результатах поиска',
      'feat_cv_analytics': 'Аналитика и статистика CV',
      'payment_method': 'Способ оплаты',
      'payment_providers': 'Платёжные провайдеры',
      'pay_card': 'Кредитная / дебетовая карта',
      'pay_card_desc': 'Visa, Mastercard, Amex',
      'pay_crypto': 'Криптовалюта',
      'pay_crypto_desc': 'BTC, ETH, USDT, SOL',
      'pay_trustly': 'Trustly',
      'pay_trustly_desc': 'Банковский перевод, быстро и безопасно',
      'pay_skrill': 'Skrill',
      'pay_skrill_desc': 'Электронный кошелёк, мгновенно',
      'pay_neteller': 'Neteller',
      'pay_neteller_desc': 'Цифровой кошелёк, низкие комиссии',
      'pay_paysafecard': 'Paysafecard',
      'pay_paysafecard_desc': 'Предоплаченная карта, анонимно',
      'pay_stripe_desc': 'Карты, Apple Pay, Google Pay',
      'pay_paypal_desc': 'Аккаунт PayPal, быстро и безопасно',
      'pay_revolut_desc': 'Аккаунт Revolut, мгновенный перевод',
      'redirect_paypal': 'Вы будете перенаправлены в PayPal для безопасной авторизации платежа.',
      'redirect_revolut': 'Вы будете перенаправлены в Revolut для мгновенной авторизации платежа.',
      'stripe_secure': 'Powered by Stripe — сертификат PCI DSS Level 1',
      'step_stripe_connect': 'Подключение к Stripe...',
      'step_paypal_connect': 'Подключение к PayPal...',
      'step_revolut_connect': 'Подключение к Revolut...',
      'subscribe_now': 'Подписаться',
      'select_plan_continue': 'Выбери тариф для продолжения',
      'confirm_subscription': 'Подтверждение подписки',
      'subscribe_to': 'Подписаться на',
      'plan_via': 'через',
      'subscribe': 'Подписаться',
      'subscribed_to': 'Подписка на',
      'payment_processing': 'Оплата обрабатывается...',
      'remind_later': 'Напомнить позже',
      'left': 'осталось',
      'free_trial': 'Бесплатный период:',
      'remaining': 'осталось',
      'confirm_order': 'Подтверждение заказа',
      'what_you_get': 'Что вы получите',
      'continue_to_payment': 'Перейти к оплате',
      'amount_to_pay': 'Сумма к оплате',
      'pay': 'Оплатить',
      'secure_payment': 'Защищено 256-битным SSL шифрованием',
      'card_details': 'Данные карты',
      'cardholder_name': 'Имя владельца карты',
      'card_number': 'Номер карты',
      'invalid_card': 'Введите корректный номер карты',
      'invalid_expiry': 'Введите ММ/ГГ',
      'invalid_cvv': 'Введите CVV',
      'select_crypto': 'Выберите криптовалюту',
      'crypto_note': 'После нажатия «Оплатить» вы получите адрес кошелька. Отправьте точную сумму в течение 30 минут.',
      'redirect_bank': 'Вы будете перенаправлены в ваш банк для безопасной авторизации платежа.',
      'enter_pin': 'Введите 16-значный PIN-код',
      'invalid_pin': 'Введите корректный 16-значный PIN',
      'paysafecard_note': 'Введите 16-значный PIN-код с вашего ваучера Paysafecard.',
      'field_required': 'Это поле обязательно',
      'processing_payment': 'Обработка платежа',
      'do_not_close': 'Пожалуйста, не закрывайте этот экран',
      'step_verifying_card': 'Проверка данных карты...',
      'step_contacting_bank': 'Связываемся с банком...',
      'step_processing_payment': 'Обработка платежа...',
      'step_confirming': 'Подтверждение подписки...',
      'step_generating_address': 'Генерация адреса кошелька...',
      'step_waiting_confirmation': 'Ожидание подтверждения блокчейна...',
      'step_connecting_bank': 'Подключение к банку...',
      'step_authorizing': 'Авторизация платежа...',
      'step_verifying_pin': 'Проверка PIN-кода...',
      'step_connecting_wallet': 'Подключение к кошельку...',
      'payment_successful': 'Оплата прошла успешно!',
      'welcome_to_plan': 'Добро пожаловать в {plan}! Ваша подписка активна.',
      'plan': 'Тариф',
      'amount_paid': 'Оплачено',
      'billing_period': 'Период оплаты',
      'monthly': 'Ежемесячно',
      'next_payment': 'Следующий платёж',
      'receipt_sent': 'Чек отправлен на ваш email',
      'your_benefits': 'Ваши преимущества',
      'start_using': 'Начать использовать GURO JOBS',
      'no_jobs_found': 'Вакансии не найдены',
      'try_different_filters': 'Попробуй другие фильтры',
      'jobs_suffix': 'Вакансии',
      // Chat screen
      'chat': 'Чат',
      'chats': 'Чаты',
      'all_channels': 'Все',
      'no_chats': 'Чатов пока нет',
      'no_chats_desc': 'Подключи мессенджеры и начни общение с работодателями',
      'type_message': 'Написать сообщение...',
      'today': 'Сегодня',
      'yesterday': 'Вчера',
      'online': 'В сети',
      'offline': 'Не в сети',
      'typing': 'печатает...',
      'sent': 'Отправлено',
      'delivered': 'Доставлено',
      'read': 'Прочитано',
      'via': 'через',
      'employer_chat': 'Работодатель',
      'agency_chat': 'Агентство',
      'support_chat': 'Поддержка',
      'unread_messages': 'непрочитанных',
      'search_chats': 'Поиск чатов...',
      'attachment': 'Вложение',
      'photo': 'Фото',
      'document': 'Документ',
      'reply': 'Ответить',
      'start_conversation': 'Начать разговор',
      // CV
      'cv_uploaded': 'CV успешно загружено!',
      'cv_removed': 'CV удалено',
      'cv_slots': 'CV загружено',
      'select_cv_categories': 'Выбери категории',
      'select_cv_categories_desc': 'Выбери вертикали для этого CV (можно несколько)',
      'upload_cv': 'Загрузить CV',
      'upload_another_cv': 'Загрузить ещё одно CV',
      'upload_cv_desc': 'Загрузи резюме чтобы\nоткликаться быстрее',
      'upload_cv_formats': 'PDF, DOC, DOCX (макс 5MB)',
      'upload_cv_max': 'Можно загрузить до 2 CV',
      'upload_cv_hint': 'Для другой вертикали или позиции',
      'uploading': 'Загрузка...',
      'choose_file': 'Выбрать файл',
      'uploaded': 'Загружено',
      'replace': 'Заменить',
      'remove': 'Удалить',
      // Workspace
      'workspace': 'Рабочее пространство',
      'notes': 'Заметки',
      'notes_desc': 'Быстрые заметки и идеи',
      'drafts': 'Черновики',
      'drafts_desc': 'Сохранённые черновики откликов',
      'integrations': 'Интеграции',
      'notion_connect': 'Notion',
      'notion_desc': 'Синхронизация заметок и досок задач',
      'obsidian_connect': 'Obsidian',
      'obsidian_desc': 'Экспорт заметок в Obsidian хранилище',
      'gdrive_connect': 'Google Drive',
      'gdrive_desc': 'Храни и синхронизируй CV файлы в облаке',
      'gsheets_connect': 'Google Sheets',
      'gsheets_desc': 'Отслеживай отклики в таблице',
      'new_note': 'Новая заметка',
      'new_draft': 'Новый черновик',
      'note_placeholder': 'Начни писать...',
      'save': 'Сохранить',
      'no_notes': 'Заметок пока нет',
      'no_notes_desc': 'Нажми + чтобы создать первую заметку',
      'no_drafts': 'Черновиков пока нет',
      'no_drafts_desc': 'Черновики откликов появятся здесь',
      'coming_soon': 'Скоро',
      'integration_soon': 'Интеграция будет доступна в ближайшее время',
      // CV Builder
      'create_cv': 'Создать резюме',
      'create_cv_desc': 'Собери профессиональное резюме',
      'cv_builder': 'Конструктор CV',
      'desired_position': 'Желаемая должность',
      'desired_position_hint': 'напр. Flutter Developer',
      'about_me': 'О себе',
      'about_me_hint': 'Краткое описание...',
      'skills': 'Навыки',
      'skills_hint': 'напр. Flutter, Dart, React...',
      'add_skill': 'Добавить',
      'work_experience': 'Опыт работы',
      'company_name': 'Компания',
      'position_title': 'Должность',
      'period': 'Период',
      'period_hint': 'напр. 2024 - н.в.',
      'description': 'Описание',
      'description_hint': 'Чем занимался?',
      'add_experience': 'Добавить опыт',
      'education': 'Образование',
      'institution': 'Учебное заведение',
      'degree': 'Специальность / Программа',
      'add_education': 'Добавить образование',
      'contact_info': 'Контакты',
      'contacts': 'Контакты',
      'contacts_hidden': 'Контакты скрыты',
      'reveal_contact': 'Открыть контакт',
      'reveal_contact_confirm': 'Открыть контакты этого кандидата?',
      'reveal_contact_cost': 'Будет использован 1 кредит из дневного лимита',
      'contact_revealed': 'Контакт открыт!',
      'no_credits_left': 'Кредиты на сегодня закончились',
      'no_credits_desc': 'Вы использовали все дневные показы контактов. Обновите тариф для увеличения лимита.',
      'credits_remaining': 'кредитов осталось на сегодня',
      'daily_limit': 'Дневной лимит',
      'upgrade_plan': 'Обновить тариф',
      'contact_email': 'Email',
      'contact_telegram': 'Telegram',
      'contact_phone': 'Телефон',
      'contact_all': 'Все контакты',
      'already_unlocked': 'Уже открыт',
      'salary_expectation': 'Желаемая зарплата',
      'salary_hint': 'напр. \$5,000',
      'preferred_geo': 'Предпочтительная локация',
      'country_hint': 'Введи страну, напр. США, Канада...',
      'add_messenger': 'Добавить мессенджер',
      'messenger_name_hint': 'напр. Viber, Signal, Discord...',
      'generate_cv': 'Создать CV',
      'cv_created': 'CV успешно создано!',
      'section_required': 'Заполни обязательные поля',
      // Organizer
      'organizer': 'Органайзер',
      'total': 'Всего',
      'interviews': 'Собеседования',
      'offers': 'Офферы',
      'status_sent': 'Отправлено',
      'status_viewed': 'Просмотрено',
      'status_interview': 'Собеседование',
      'status_offer': 'Оффер',
      'status_rejected': 'Отказ',
      'applied': 'Отправлено',
      'timeline': 'История',
      'meetings': 'Встречи',
      'add_meeting': 'Добавить встречу',
      'meeting_type': 'Тип',
      'meeting_date': 'Дата',
      'meeting_time': 'Время',
      'meeting_link': 'Ссылка',
      'meeting_video': 'Видеозвонок',
      'meeting_phone': 'Телефон',
      'meeting_onsite': 'В офисе',
      'add_note': 'Добавить заметку',
      'note_hint': 'Напиши заметку...',
      'no_meetings': 'Нет запланированных встреч',
      'no_notes_app': 'Заметок пока нет',
      'delete': 'Удалить',
      'edit': 'Редактировать',
      'done': 'Готово',
      'schedule_meeting': 'Запланировать встречу',
      'details': 'Подробности',
      'status_change': 'Статус изменён на',
      'application_sent': 'Заявка отправлена',
      'cv_viewed': 'CV просмотрено',
      'interview_scheduled': 'Собеседование назначено',
      'offer_received': 'Получен оффер',
      'rejected_info': 'Заявка отклонена',
      'open_link': 'Открыть ссылку',
      // Filters
      'filters': 'Фильтры',
      'salary': 'Зарплата',
      'salary_range': 'Диапазон зарплаты',
      'from': 'От',
      'to': 'До',
      'experience': 'Опыт работы',
      'no_experience': 'Без опыта',
      'year_1': '1 год',
      'years_2': '2 года',
      'years_3': '3 года',
      'years_4': '4 года',
      'years_5': '5 лет',
      'years_6': '6 лет',
      'years_7': '7 лет',
      'years_8': '8 лет',
      'years_9': '9 лет',
      'years_10_plus': '10+ лет',
      'work_setup': 'Формат работы',
      'office': 'Офис',
      'hybrid': 'Гибрид',
      'verticals': 'Вертикали',
      'english_level': 'Английский',
      'no_english': 'Нет английского',
      'beginner': 'Beginner/Elementary',
      'pre_intermediate': 'Pre-Intermediate',
      'intermediate': 'Intermediate',
      'upper_intermediate': 'Upper-Intermediate',
      'advanced': 'Advanced/Fluent',
      'proficient': 'Proficient',
      'native_speaker': 'Native Speaker',
      'geo': 'Гео',
      'worldwide': 'Весь мир',
      'eu_countries': 'Страны ЕС',
      'other_countries': 'Другие страны',
      'hide_with_replies': 'Не показывать вакансии с откликами/предложениями',
      'show_salary_range': 'Показывать вакансии с зарплатной вилкой',
      'apply_filters': 'Применить',
      'reset_filters': 'Сбросить',
      'filters_applied': 'Фильтры применены',
      // Employer
      'emp_welcome': 'Управляйте вакансиями',
      'emp_my_jobs': 'Мои вакансии',
      'emp_candidates': 'Кандидаты',
      'emp_company': 'Компания',
      'emp_active_jobs': 'Активные',
      'emp_total_apps': 'Отклики',
      'emp_new_today': 'Новые сегодня',
      'emp_job_views': 'Просмотры',
      'emp_hired': 'Наняты',
      'emp_quick_actions': 'Быстрые действия',
      'emp_post_job': 'Разместить',
      'emp_search_talent': 'Поиск талантов',
      'emp_recent_apps': 'Последние отклики',
      'emp_status_active': 'Активна',
      'emp_status_paused': 'Приостановлена',
      'emp_status_closed': 'Закрыта',
      'emp_status_draft': 'Черновик',
      'emp_no_jobs': 'Вакансии не найдены',
      'emp_no_candidates': 'Кандидаты не найдены',
      'emp_all_positions': 'Все позиции',
      'emp_cand_new': 'Новый',
      'emp_cand_reviewed': 'Просмотрен',
      'emp_cand_interview': 'Собеседование',
      'emp_cand_hired': 'Нанят',
      'emp_cand_rejected': 'Отклонён',
      'emp_applied_for': 'Отклик на',
      'emp_change_status': 'Изменить статус',
      'emp_write_msg': 'Написать',
      'emp_view_cv': 'Смотреть CV',
      'emp_view_apps': 'Отклики',
      'emp_posted': 'Размещена',
      'emp_post_new_job': 'Новая вакансия',
      'emp_job_title': 'Название',
      'emp_job_title_hint': 'напр. Senior Affiliate Manager',
      'emp_vertical': 'Вертикаль',
      'emp_work_type': 'Тип работы',
      'emp_job_desc_hint': 'Опишите роль, требования...',
      'emp_publish_job': 'Опубликовать',
      'emp_job_created': 'Вакансия опубликована!',
      'emp_title_required': 'Укажите название вакансии',
      'preview_and_publish': 'Предпросмотр и публикация',
      'job_preview': 'Предпросмотр вакансии',
      'job_preview_note': 'Так кандидаты увидят вашу вакансию. Проверьте все данные перед публикацией.',
      'requirements': 'Требования',
      'requirements_hint': 'Список требований (по одному на строку)',
      'tags': 'Теги / Ключевые слова',
      'tags_hint': 'flutter, dart, react (через запятую)',
      'publishing_job': 'Публикация вакансии...',
      'updating_job': 'Обновление вакансии...',
      'step_validating_job': 'Проверка данных вакансии...',
      'step_checking_plan': 'Проверка лимитов тарифа...',
      'step_publishing': 'Публикация на доске вакансий...',
      'step_indexing': 'Индексация для поиска...',
      'job_published': 'Вакансия опубликована!',
      'job_updated': 'Вакансия обновлена!',
      'active': 'Активна',
      'public': 'Публичная',
      'visibility': 'Видимость',
      'posted_at': 'Опубликована',
      'job_visible_note': 'Ваша вакансия видна тысячам iGaming-специалистов по всему миру.',
      'what_happens_next': 'Что дальше?',
      'next_candidates_see': 'Кандидаты увидят вашу вакансию в поиске и ленте.',
      'next_applications': 'Вы получите отклики во вкладке Кандидаты.',
      'next_review': 'Просматривайте кандидатов, открывайте контакты и нанимайте лучших!',
      'back_to_dashboard': 'На главную',
      'emp_company_profile': 'Профиль компании',
      'emp_subscription': 'Подписка и оплата',
      // Admin
      'adm_panel': 'Админ',
      'adm_welcome': 'Панель управления платформой',
      'adm_platform_stats': 'Статистика платформы',
      'adm_total_users': 'Всего юзеров',
      'adm_total_jobs': 'Всего вакансий',
      'adm_companies': 'Компании',
      'adm_new_today': 'Новых сегодня',
      'adm_revenue': 'Доход',
      'adm_payments': 'Платежи',
      'adm_reports': 'Жалобы',
      'adm_quick_actions': 'Быстрые действия',
      'adm_manage_users': 'Управление юзерами',
      'adm_moderate_jobs': 'Модерация вакансий',
      'adm_analytics': 'Аналитика',
      'adm_pending_approvals': 'Ожидают одобрения',
      'adm_recent_activity': 'Последняя активность',
      'adm_users': 'Пользователи',
      'adm_search_users': 'Поиск по имени или email...',
      'adm_candidates': 'Кандидаты',
      'adm_employers': 'Работодатели',
      'adm_admins': 'Админы',
      'adm_active': 'Активен',
      'adm_pending': 'Ожидает',
      'adm_banned': 'Заблокирован',
      'adm_no_users': 'Пользователи не найдены',
      'adm_registered': 'Регистрация',
      'adm_last_login': 'Последний вход',
      'adm_jobs_applied': 'Откликов',
      'adm_approve': 'Одобрить',
      'adm_reject': 'Отклонить',
      'adm_message': 'Написать',
      'adm_ban': 'Заблокировать',
      'adm_unban': 'Разблокировать',
      'adm_job_moderation': 'Модерация вакансий',
      'adm_approved': 'Одобрена',
      'adm_rejected_status': 'Отклонена',
      'adm_featured': 'Продвигаемая',
      'adm_security': 'Безопасность',
      'adm_subscriptions': 'Подписки',
      'adm_subscribers': 'подписчиков',
      'all': 'Все',
      'expired': 'Истёк',
      'cancelled': 'Отменён',
      'change_plan': 'Сменить тариф',
      'extend': 'Продлить',
      'extend_confirm': 'Продлить подписку на:',
      'extended_by': 'продлён на',
      'block': 'Заблокировать',
      'block_confirm': 'Заблокировать компанию? Подписка будет отменена.',
      'blocked': 'заблокирован',
      'adm_approve_confirm': 'Пользователь получит полный доступ к платформе.',
      'adm_approved': 'одобрен',
      'adm_reject_reason': 'Укажите причину отклонения:',
      'adm_reason_hint': 'Введите причину...',
      'adm_ban_confirm': 'Пользователь будет заблокирован на платформе.',
      'adm_unban_confirm': 'Восстановить доступ для этого пользователя?',
      'adm_unbanned': 'разблокирован',
      'adm_approve_job_confirm': 'Вакансия будет видна всем кандидатам.',
      'adm_reject_job_reason': 'Причина отклонения вакансии:',
      'adm_feature_confirm': 'Показывать вакансию в топе поиска?',
      'pending': 'Ожидает',
      'resolved': 'Решено',
      'documents': 'Документы',
      'reason': 'Причина',
      'reported_by': 'Пожаловался',
      'adm_verify_approve': 'Верифицировать работодателя? Он получит значок верификации.',
      'adm_take_action': 'Принять меры',
      'adm_warn_user': 'Отправить предупреждение',
      'adm_warning_sent': 'Предупреждение отправлено',
      'adm_remove_content': 'Удалить контент',
      'adm_content_removed': 'Контент удалён',
      'adm_dismiss': 'Отклонить',
      'adm_report_dismissed': 'Жалоба отклонена',
      'adm_tools': 'ИНСТРУМЕНТЫ АДМИНА',
      'adm_database': 'Система и база данных',
      'adm_verification': 'Верификация',
      'adm_general': 'ОБЩЕЕ',
      'what_is_it': 'Что это?',
      'key_roles': 'Ключевые роли',
      'industry_stats': 'Статистика индустрии',
      'skills_needed': 'Нужные навыки',
      'want_to_learn': 'Хотите узнать больше?',
      'guro_school_desc': 'Начни карьеру в iGaming с профессиональными курсами Guro School',
      'go_to_guro_school': 'Guro School',
      'admin_panel': 'Панель админа',
      'admin_login_desc': 'Вход с учётными данными администратора',
      'admin_only_error': 'Доступ запрещён. Только для админов.',
      'find_job_or_hire': 'Найти работу или нанять',
      'candidate_employer_desc': 'Для кандидатов и работодателей',
      'choose_how_to_continue': 'Выберите как продолжить',
      // Jarvis
      'jarvis': 'Джарвис',
      'jarvis_hello': 'Привет! Я Джарвис, ваш AI-ассистент.',
      'jarvis_hint': 'Попробуйте: "Статистика" или "Покажи вакансии"',
      'jarvis_ask': 'Спросите Джарвиса...',
      'jarvis_listening': 'Слушаю...',
      'jarvis_processing': 'Обработка...',
      'jarvis_speaking': 'Говорю...',
      'jarvis_error': 'Ошибка',
      'jarvis_connection_error': 'Ошибка соединения. Попробуйте ещё раз.',
      // Filters
      'communication_preferences': 'Предпочтения общения',
      'priority_language': 'Приоритетный язык',
      'acceptable_languages': 'Приемлемые языки (1-3)',
      'select_language': 'Выберите язык',
      'select_languages_hint': 'Нажмите для выбора языков',
      'candidate_filters': 'Страна и гражданство',
      'citizenship_country': 'Страна гражданства',
      'select_country': 'Выберите страну',
      'in_citizenship_country': 'Вы находитесь в стране гражданства?',
      'blocked_company_countries': 'Отсечь страны компаний',
      'blocked_countries_hint': 'Страны, в которых не хотите работать',
      'employer_filters': 'Предпочтения по кандидатам',
      'main_office_countries': 'Страна главного офиса',
      'select_countries': 'Выберите страны',
      'blocked_candidate_citizenships': 'Отсечь гражданства кандидатов',
      'blocked_citizenships_hint': 'Гражданства, которым нечего предложить',
      'candidate_location_pref': 'Показать кандидатов',
      'all_candidates': 'Все варианты',
      'outside_citizenship': 'За пределами страны',
      'save_changes': 'Сохранить',
      'profile_updated': 'Профиль обновлён!',
    },
    'uk': {
      'app_name': 'GURO JOBS',
      'get_started': 'Почати',
      'already_have_account': 'Вже є акаунт? Увійти',
      'home': 'Головна',
      'jobs': 'Вакансії',
      'applications': 'Відгуки',
      'profile': 'Профіль',
      'hello': 'Привіт',
      'find_dream_job': 'Знайди роботу мрії в iGaming',
      'search_jobs': 'Пошук вакансій, компаній...',
      'jobs_available': 'Вакансій',
      'profile_views': 'Перегляди',
      'saved': 'Збережені',
      'interviews': 'Співбесіди',
      'popular_categories': 'Популярні категорії',
      'recent_jobs': 'Нові вакансії',
      'see_all': 'Усі',
      'find_jobs': 'Пошук вакансій',
      'search_by_title': 'Пошук за назвою, навичкою...',
      'all': 'Усі',
      'remote': 'Віддалено',
      'full_time': 'Повна',
      'senior': 'Senior',
      'my_applications': 'Мої відгуки',
      'track_applications': 'Відстежуй свої заявки',
      'no_applications': 'Відгуків поки немає',
      'start_applying': 'Відгукуйся на вакансії та\nвідстежуй прогрес тут',
      'browse_jobs': 'Дивитися вакансії',
      'candidate': 'Кандидат',
      'employer': 'Роботодавець',
      'admin': 'Адмін',
      'select_role': 'Я...',
      'complete_profile': 'Заповни профіль',
      'complete_profile_desc': 'Додай навички, досвід та CV щоб тебе помітили',
      'edit_profile': 'Редагувати профіль',
      'my_cv': 'Моє CV / Резюме',
      'saved_jobs': 'Збережені',
      'notifications': 'Сповіщення',
      'settings': 'Налаштування',
      'help_support': 'Допомога',
      'help': 'Допомога',
      'language': 'Мова',
      'dark_mode': 'Темна тема',
      'dark_mode_desc': 'Перемкнути на темну тему',
      'push_notifications': 'Push сповіщення',
      'push_notifications_desc': 'Сповіщення про нові вакансії',
      'email_notifications': 'Email сповіщення',
      'email_notifications_desc': 'Отримувати вакансії на email',
      'appearance': 'Зовнішній вигляд',
      'account': 'Акаунт',
      'change_password': 'Змінити пароль',
      'clear_app_data': 'Очистити дані',
      'clear_app_data_confirm': 'Ви вийдете з акаунту і всі налаштування будуть скинуті. Продовжити?',
      'clear': 'Очистити',
      'delete_account': 'Видалити акаунт',
      'delete_account_confirm': 'Ця дія незворотня. Всі ваші дані будуть видалені.',
      'delete': 'Видалити',
      'location': 'Локація',
      'logout': 'Вийти',
      'logout_confirm': 'Ви впевнені що хочете вийти?',
      'cancel': 'Скасувати',
      'join_community': 'Приєднатися до спільноти',
      'join_community_desc': 'Спілкуйся з iGaming професіоналами',
      'welcome_back': 'З поверненням',
      'create_account': 'Створити акаунт',
      'sign_in_subtitle': 'Увійди щоб знайти роботу в iGaming',
      'register_subtitle': 'Приєднуйся до GURO JOBS',
      'register': 'Реєстрація',
      'sign_in': 'Увійти',
      'full_name': 'Повне ім\'я',
      'email_address': 'Email',
      'password': 'Пароль',
      'confirm_password': 'Повтори пароль',
      'no_account': 'Немає акаунту? ',
      'have_account': 'Вже є акаунт? ',
      'forgot_password': 'Забули пароль?',
      'forgot_password_title': 'Скидання паролю',
      'forgot_password_desc': 'Введіть email і ми надішлемо посилання для скидання',
      'send_reset_link': 'Надіслати посилання',
      'reset_sent': 'Посилання для скидання надіслано на ваш email',
      'back_to_login': 'Назад до входу',
      'terms_privacy': 'Умови та політика',
      'terms_read': 'Прочитайте та прийміть умови перед продовженням',
      'scroll_hint': 'Прокрутіть вниз щоб прочитати',
      'agree_terms': 'Я прочитав та погоджуюсь з Умовами використання та Політикою конфіденційності',
      'accept_continue': 'Прийняти та продовжити',
      'igaming_platform': 'Робота в найприбутковіших вертикалях світу',
      'gambling': 'Гемблінг',
      'betting': 'Бетінг',
      'crypto': 'Крипта',
      'nutra': 'Нутра',
      'dating': 'Дейтінг',
      'ecommerce': 'E-commerce',
      'fintech': 'FinTech',
      'other': 'Інше',
      'connection_error': 'Помилка підключення. Спробуйте знову.',
      'invalid_credentials': 'Невірні дані',
      'enter_name': 'Введіть ім\'я',
      'enter_email': 'Введіть email',
      'valid_email': 'Введіть коректний email',
      'enter_password': 'Введіть пароль',
      'password_min': 'Мінімум 8 символів',
      'passwords_mismatch': 'Паролі не збігаються',
      'phone': 'Телефон',
      'telegram': 'Телеграм',
      'or': 'або',
      'name_hint': 'Іван Іваненко',
      'email_hint': 'ваш@email.com',
      'password_hint': 'Мінімум 8 символів',
      'confirm_hint': 'Повтори пароль',
      'phone_hint': '+48 000 000 000',
      'telegram_hint': '@username',
      // Connections screen
      'connections': 'Підключення',
      'messengers': 'Месенджери',
      'messengers_desc': 'Підключи месенджери для отримання сповіщень та спілкування з роботодавцями',
      'social_networks': 'Соціальні мережі',
      'social_desc': 'Прив\'яжи соцмережі щоб підвищити видимість для роботодавців',
      'connected': 'Підключено',
      'disconnected': 'відключено',
      'connect': 'Підключити',
      'connect_title': 'Підключити',
      'connect_scan_desc': 'Скануй QR-код або натисни підключити для прив\'язки',
      'scan_to_connect': 'Скануй для підключення',
      'connected_success': 'успішно підключено!',
      'telegram_name': 'Telegram',
      'telegram_desc': 'Миттєві сповіщення про вакансії через Telegram бот',
      'whatsapp_name': 'WhatsApp',
      'whatsapp_desc': 'Отримуй сповіщення та повідомлення від роботодавців',
      'viber_name': 'Viber',
      'viber_desc': 'Швидкий зв\'язок з роботодавцями',
      'email_name': 'Email',
      'email_desc': 'Отримуй пропозиції роботи та оновлення по email',
      'signal_name': 'Signal',
      'signal_desc': 'Безпечний обмін повідомленнями з роботодавцями',
      'linkedin_name': 'LinkedIn',
      'linkedin_desc': 'Імпортуй професійний профіль та контакти',
      'github_name': 'GitHub',
      'github_desc': 'Покажи своє технічне портфоліо',
      'twitter_name': 'X (Twitter)',
      'twitter_desc': 'Слідкуй за iGaming компаніями та вакансіями',
      'facebook_name': 'Facebook',
      'facebook_desc': 'Приєднуйся до iGaming спільнот',
      'instagram_name': 'Instagram',
      'instagram_desc': 'Ділися професійним шляхом',
      'discord_name': 'Discord',
      'discord_desc': 'Вступай до iGaming серверів',
      // Billing screen
      'billing_plans': 'Тарифи та оплата',
      'choose_plan': 'Обери свій тариф',
      'choose_plan_desc': 'Розблокуй преміум функції та пришвидш пошук роботи',
      'trial_active': 'Безкоштовний період',
      'trial_expired': 'Пробний період закінчився',
      'trial_remaining': 'Залишилось часу для вибору тарифу:',
      'trial_upgrade': 'Онови тариф щоб продовжити використання преміум функцій',
      'plan_basic': 'Базовий',
      'plan_premium': 'Преміум',
      'plan_vip': 'VIP',
      'popular': 'ПОПУЛЯРНИЙ',
      'per_month': '/міс',
      'days': 'днів',
      'plan_basic_contacts': 'До 10 контактів кандидатів на добу',
      'plan_basic_desc': 'Перегляд профілів та відкриття контактів',
      'plan_premium_contacts': 'До 50 контактів на всю команду на добу',
      'plan_premium_team': 'Командний доступ: до 3 користувачів',
      'plan_premium_linkedin': 'LinkedIn профілі кандидатів',
      'plan_premium_desc': 'Підключіть членів команди до вашого тарифу',
      'plan_vip_contacts': 'Необмежена кількість контактів',
      'plan_vip_team': 'Командний доступ: до 5 користувачів',
      'plan_vip_bot': 'Telegram бот: авто-сповіщення про нові резюме за вашими вакансіями',
      'plan_vip_desc': 'Пошук кандидатів у реальному часі з миттєвими сповіщеннями',
      'feat_email_alerts': 'Email сповіщення про вакансії',
      'feat_priority_search': 'Пріоритет у результатах пошуку',
      'feat_cv_analytics': 'Аналітика та статистика CV',
      'payment_method': 'Спосіб оплати',
      'payment_providers': 'Платіжні провайдери',
      'pay_card': 'Кредитна / дебетова картка',
      'pay_card_desc': 'Visa, Mastercard, Amex',
      'pay_crypto': 'Криптовалюта',
      'pay_crypto_desc': 'BTC, ETH, USDT, SOL',
      'pay_trustly': 'Trustly',
      'pay_trustly_desc': 'Банківський переказ, швидко та безпечно',
      'pay_skrill': 'Skrill',
      'pay_skrill_desc': 'Електронний гаманець, миттєво',
      'pay_neteller': 'Neteller',
      'pay_neteller_desc': 'Цифровий гаманець, низькі комісії',
      'pay_paysafecard': 'Paysafecard',
      'pay_paysafecard_desc': 'Передплачена картка, анонімно',
      'pay_stripe_desc': 'Картки, Apple Pay, Google Pay',
      'pay_paypal_desc': 'Акаунт PayPal, швидко та безпечно',
      'pay_revolut_desc': 'Акаунт Revolut, миттєвий переказ',
      'redirect_paypal': 'Вас буде перенаправлено до PayPal для безпечної авторизації платежу.',
      'redirect_revolut': 'Вас буде перенаправлено до Revolut для миттєвої авторизації платежу.',
      'stripe_secure': 'Powered by Stripe — сертифікат PCI DSS Level 1',
      'step_stripe_connect': 'Підключення до Stripe...',
      'step_paypal_connect': 'Підключення до PayPal...',
      'step_revolut_connect': 'Підключення до Revolut...',
      'subscribe_now': 'Підписатися',
      'select_plan_continue': 'Обери тариф для продовження',
      'confirm_subscription': 'Підтвердження підписки',
      'subscribe_to': 'Підписатися на',
      'plan_via': 'через',
      'subscribe': 'Підписатися',
      'subscribed_to': 'Підписка на',
      'payment_processing': 'Оплата обробляється...',
      'remind_later': 'Нагадати пізніше',
      'left': 'залишилось',
      'free_trial': 'Безкоштовний період:',
      'remaining': 'залишилось',
      'confirm_order': 'Підтвердження замовлення',
      'what_you_get': 'Що ви отримаєте',
      'continue_to_payment': 'Перейти до оплати',
      'amount_to_pay': 'Сума до оплати',
      'pay': 'Оплатити',
      'secure_payment': 'Захищено 256-бітним SSL шифруванням',
      'card_details': 'Дані картки',
      'cardholder_name': 'Ім\'я власника картки',
      'card_number': 'Номер картки',
      'invalid_card': 'Введіть коректний номер картки',
      'invalid_expiry': 'Введіть ММ/РР',
      'invalid_cvv': 'Введіть CVV',
      'select_crypto': 'Оберіть криптовалюту',
      'crypto_note': 'Після натискання «Оплатити» ви отримаєте адресу гаманця. Надішліть точну суму протягом 30 хвилин.',
      'redirect_bank': 'Вас буде перенаправлено до вашого банку для безпечної авторизації платежу.',
      'enter_pin': 'Введіть 16-значний PIN-код',
      'invalid_pin': 'Введіть коректний 16-значний PIN',
      'paysafecard_note': 'Введіть 16-значний PIN-код з вашого ваучера Paysafecard.',
      'field_required': 'Це поле обов\'язкове',
      'processing_payment': 'Обробка платежу',
      'do_not_close': 'Будь ласка, не закривайте цей екран',
      'step_verifying_card': 'Перевірка даних картки...',
      'step_contacting_bank': 'Зв\'язуємося з банком...',
      'step_processing_payment': 'Обробка платежу...',
      'step_confirming': 'Підтвердження підписки...',
      'step_generating_address': 'Генерація адреси гаманця...',
      'step_waiting_confirmation': 'Очікування підтвердження блокчейну...',
      'step_connecting_bank': 'Підключення до банку...',
      'step_authorizing': 'Авторизація платежу...',
      'step_verifying_pin': 'Перевірка PIN-коду...',
      'step_connecting_wallet': 'Підключення до гаманця...',
      'payment_successful': 'Оплата пройшла успішно!',
      'welcome_to_plan': 'Ласкаво просимо до {plan}! Ваша підписка активна.',
      'plan': 'Тариф',
      'amount_paid': 'Оплачено',
      'billing_period': 'Період оплати',
      'monthly': 'Щомісяця',
      'next_payment': 'Наступний платіж',
      'receipt_sent': 'Чек надіслано на ваш email',
      'your_benefits': 'Ваші переваги',
      'start_using': 'Почати використовувати GURO JOBS',
      'no_jobs_found': 'Вакансії не знайдено',
      'try_different_filters': 'Спробуй інші фільтри',
      'jobs_suffix': 'Вакансії',
      // Chat screen
      'chat': 'Чат',
      'chats': 'Чати',
      'all_channels': 'Всі',
      'no_chats': 'Чатів поки немає',
      'no_chats_desc': 'Підключи месенджери та почни спілкування з роботодавцями',
      'type_message': 'Написати повідомлення...',
      'today': 'Сьогодні',
      'yesterday': 'Вчора',
      'online': 'В мережі',
      'offline': 'Не в мережі',
      'typing': 'друкує...',
      'sent': 'Відправлено',
      'delivered': 'Доставлено',
      'read': 'Прочитано',
      'via': 'через',
      'employer_chat': 'Роботодавець',
      'agency_chat': 'Агентство',
      'support_chat': 'Підтримка',
      'unread_messages': 'непрочитаних',
      'search_chats': 'Пошук чатів...',
      'attachment': 'Вкладення',
      'photo': 'Фото',
      'document': 'Документ',
      'reply': 'Відповісти',
      'start_conversation': 'Почати розмову',
      // CV
      'cv_uploaded': 'CV успішно завантажено!',
      'cv_removed': 'CV видалено',
      'cv_slots': 'CV завантажено',
      'select_cv_categories': 'Обери категорії',
      'select_cv_categories_desc': 'Обери вертикалі для цього CV (можна кілька)',
      'upload_cv': 'Завантажити CV',
      'upload_another_cv': 'Завантажити ще одне CV',
      'upload_cv_desc': 'Завантаж резюме щоб\nвідгукуватися швидше',
      'upload_cv_formats': 'PDF, DOC, DOCX (макс 5MB)',
      'upload_cv_max': 'Можна завантажити до 2 CV',
      'upload_cv_hint': 'Для іншої вертикалі або позиції',
      'uploading': 'Завантаження...',
      'choose_file': 'Обрати файл',
      'uploaded': 'Завантажено',
      'replace': 'Замінити',
      'remove': 'Видалити',
      // Workspace
      'workspace': 'Робочий простір',
      'notes': 'Нотатки',
      'notes_desc': 'Швидкі нотатки та ідеї',
      'drafts': 'Чернетки',
      'drafts_desc': 'Збережені чернетки відгуків',
      'integrations': 'Інтеграції',
      'notion_connect': 'Notion',
      'notion_desc': 'Синхронізація нотаток та дошок завдань',
      'obsidian_connect': 'Obsidian',
      'obsidian_desc': 'Експорт нотаток до Obsidian сховища',
      'gdrive_connect': 'Google Drive',
      'gdrive_desc': 'Зберігай та синхронізуй CV файли у хмарі',
      'gsheets_connect': 'Google Sheets',
      'gsheets_desc': 'Відстежуй відгуки у таблиці',
      'new_note': 'Нова нотатка',
      'new_draft': 'Нова чернетка',
      'note_placeholder': 'Почни писати...',
      'save': 'Зберегти',
      'no_notes': 'Нотаток поки немає',
      'no_notes_desc': 'Натисни + щоб створити першу нотатку',
      'no_drafts': 'Чернеток поки немає',
      'no_drafts_desc': 'Чернетки відгуків з\'являться тут',
      'coming_soon': 'Скоро',
      'integration_soon': 'Інтеграція буде доступна найближчим часом',
      // CV Builder
      'create_cv': 'Створити резюме',
      'create_cv_desc': 'Створи професійне резюме',
      'cv_builder': 'Конструктор CV',
      'desired_position': 'Бажана посада',
      'desired_position_hint': 'напр. Flutter Developer',
      'about_me': 'Про себе',
      'about_me_hint': 'Короткий опис...',
      'skills': 'Навички',
      'skills_hint': 'напр. Flutter, Dart, React...',
      'add_skill': 'Додати',
      'work_experience': 'Досвід роботи',
      'company_name': 'Компанія',
      'position_title': 'Посада',
      'period': 'Період',
      'period_hint': 'напр. 2024 - тепер',
      'description': 'Опис',
      'description_hint': 'Чим займався?',
      'add_experience': 'Додати досвід',
      'education': 'Освіта',
      'institution': 'Навчальний заклад',
      'degree': 'Спеціальність / Програма',
      'add_education': 'Додати освіту',
      'contact_info': 'Контакти',
      'contacts': 'Контакти',
      'contacts_hidden': 'Контакти приховані',
      'reveal_contact': 'Відкрити контакт',
      'reveal_contact_confirm': 'Відкрити контакти цього кандидата?',
      'reveal_contact_cost': 'Буде використано 1 кредит з денного ліміту',
      'contact_revealed': 'Контакт відкрито!',
      'no_credits_left': 'Кредити на сьогодні закінчились',
      'no_credits_desc': 'Ви використали всі денні покази контактів. Оновіть тариф для збільшення ліміту.',
      'credits_remaining': 'кредитів залишилось на сьогодні',
      'daily_limit': 'Денний ліміт',
      'upgrade_plan': 'Оновити тариф',
      'contact_email': 'Email',
      'contact_telegram': 'Telegram',
      'contact_phone': 'Телефон',
      'contact_all': 'Всі контакти',
      'already_unlocked': 'Вже відкрито',
      'salary_expectation': 'Бажана зарплата',
      'salary_hint': 'напр. \$5,000',
      'preferred_geo': 'Бажана локація',
      'country_hint': 'Введи країну, напр. США, Канада...',
      'add_messenger': 'Додати месенджер',
      'messenger_name_hint': 'напр. Viber, Signal, Discord...',
      'generate_cv': 'Створити CV',
      'cv_created': 'CV успішно створено!',
      'section_required': 'Заповни обов\'язкові поля',
      // Organizer
      'organizer': 'Органайзер',
      'total': 'Всього',
      'interviews': 'Співбесіди',
      'offers': 'Офери',
      'status_sent': 'Надіслано',
      'status_viewed': 'Переглянуто',
      'status_interview': 'Співбесіда',
      'status_offer': 'Офер',
      'status_rejected': 'Відмова',
      'applied': 'Надіслано',
      'timeline': 'Історія',
      'meetings': 'Зустрічі',
      'add_meeting': 'Додати зустріч',
      'meeting_type': 'Тип',
      'meeting_date': 'Дата',
      'meeting_time': 'Час',
      'meeting_link': 'Посилання',
      'meeting_video': 'Відеодзвінок',
      'meeting_phone': 'Телефон',
      'meeting_onsite': 'В офісі',
      'add_note': 'Додати нотатку',
      'note_hint': 'Напиши нотатку...',
      'no_meetings': 'Немає запланованих зустрічей',
      'no_notes_app': 'Нотаток поки немає',
      'delete': 'Видалити',
      'edit': 'Редагувати',
      'done': 'Готово',
      'schedule_meeting': 'Запланувати зустріч',
      'details': 'Деталі',
      'status_change': 'Статус змінено на',
      'application_sent': 'Заявку надіслано',
      'cv_viewed': 'CV переглянуто',
      'interview_scheduled': 'Співбесіду призначено',
      'offer_received': 'Отримано офер',
      'rejected_info': 'Заявку відхилено',
      'open_link': 'Відкрити посилання',
      // Filters
      'filters': 'Фільтри',
      'salary': 'Зарплата',
      'salary_range': 'Діапазон зарплати',
      'from': 'Від',
      'to': 'До',
      'experience': 'Досвід роботи',
      'no_experience': 'Без досвіду',
      'year_1': '1 рік',
      'years_2': '2 роки',
      'years_3': '3 роки',
      'years_4': '4 роки',
      'years_5': '5 років',
      'years_6': '6 років',
      'years_7': '7 років',
      'years_8': '8 років',
      'years_9': '9 років',
      'years_10_plus': '10+ років',
      'work_setup': 'Формат роботи',
      'office': 'Офіс',
      'hybrid': 'Гібрид',
      'verticals': 'Вертикалі',
      'english_level': 'Англійська',
      'no_english': 'Без англійської',
      'beginner': 'Beginner/Elementary',
      'pre_intermediate': 'Pre-Intermediate',
      'intermediate': 'Intermediate',
      'upper_intermediate': 'Upper-Intermediate',
      'advanced': 'Advanced/Fluent',
      'proficient': 'Proficient',
      'native_speaker': 'Native Speaker',
      'geo': 'Гео',
      'worldwide': 'Увесь світ',
      'eu_countries': 'Країни ЄС',
      'other_countries': 'Інші країни',
      'hide_with_replies': 'Не показувати вакансії з відгуками/пропозиціями',
      'show_salary_range': 'Показувати вакансії із зарплатною вилкою',
      'apply_filters': 'Застосувати',
      'reset_filters': 'Скинути',
      'filters_applied': 'Фільтри застосовано',
      // Employer
      'emp_welcome': 'Керуйте вакансіями',
      'emp_my_jobs': 'Мої вакансії',
      'emp_candidates': 'Кандидати',
      'emp_company': 'Компанія',
      'emp_active_jobs': 'Активні',
      'emp_total_apps': 'Відгуки',
      'emp_new_today': 'Нові сьогодні',
      'emp_job_views': 'Перегляди',
      'emp_hired': 'Найняті',
      'emp_quick_actions': 'Швидкі дії',
      'emp_post_job': 'Розмістити',
      'emp_search_talent': 'Пошук талантів',
      'emp_recent_apps': 'Останні відгуки',
      'emp_status_active': 'Активна',
      'emp_status_paused': 'Призупинена',
      'emp_status_closed': 'Закрита',
      'emp_status_draft': 'Чернетка',
      'emp_no_jobs': 'Вакансії не знайдено',
      'emp_no_candidates': 'Кандидатів не знайдено',
      'emp_all_positions': 'Усі позиції',
      'emp_cand_new': 'Новий',
      'emp_cand_reviewed': 'Переглянутий',
      'emp_cand_interview': 'Співбесіда',
      'emp_cand_hired': 'Найнятий',
      'emp_cand_rejected': 'Відхилений',
      'emp_applied_for': 'Відгук на',
      'emp_change_status': 'Змінити статус',
      'emp_write_msg': 'Написати',
      'emp_view_cv': 'Дивитись CV',
      'emp_view_apps': 'Відгуки',
      'emp_posted': 'Розміщена',
      'emp_post_new_job': 'Нова вакансія',
      'emp_job_title': 'Назва',
      'emp_job_title_hint': 'напр. Senior Affiliate Manager',
      'emp_vertical': 'Вертикаль',
      'emp_work_type': 'Тип роботи',
      'emp_job_desc_hint': 'Опишіть роль, вимоги...',
      'emp_publish_job': 'Опублікувати',
      'emp_job_created': 'Вакансію опубліковано!',
      'emp_title_required': 'Вкажіть назву вакансії',
      'preview_and_publish': 'Попередній перегляд і публікація',
      'job_preview': 'Попередній перегляд',
      'job_preview_note': 'Так кандидати побачать вашу вакансію. Перевірте всі дані перед публікацією.',
      'requirements': 'Вимоги',
      'requirements_hint': 'Список вимог (по одній на рядок)',
      'tags': 'Теги / Ключові слова',
      'tags_hint': 'flutter, dart, react (через кому)',
      'publishing_job': 'Публікація вакансії...',
      'updating_job': 'Оновлення вакансії...',
      'step_validating_job': 'Перевірка даних вакансії...',
      'step_checking_plan': 'Перевірка лімітів тарифу...',
      'step_publishing': 'Публікація на дошці вакансій...',
      'step_indexing': 'Індексація для пошуку...',
      'job_published': 'Вакансію опубліковано!',
      'job_updated': 'Вакансію оновлено!',
      'active': 'Активна',
      'public': 'Публічна',
      'visibility': 'Видимість',
      'posted_at': 'Опубліковано',
      'job_visible_note': 'Ваша вакансія видна тисячам iGaming-фахівців по всьому світу.',
      'what_happens_next': 'Що далі?',
      'next_candidates_see': 'Кандидати побачать вашу вакансію у пошуку та стрічці.',
      'next_applications': 'Ви отримаєте відгуки у вкладці Кандидати.',
      'next_review': 'Переглядайте кандидатів, відкривайте контакти та наймайте найкращих!',
      'back_to_dashboard': 'На головну',
      'emp_company_profile': 'Профіль компанії',
      'emp_subscription': 'Підписка та оплата',
      // Admin
      'adm_panel': 'Адмін',
      'adm_welcome': 'Панель управління платформою',
      'adm_platform_stats': 'Статистика платформи',
      'adm_total_users': 'Усього юзерів',
      'adm_total_jobs': 'Усього вакансій',
      'adm_companies': 'Компанії',
      'adm_new_today': 'Нових сьогодні',
      'adm_revenue': 'Дохід',
      'adm_payments': 'Платежі',
      'adm_reports': 'Скарги',
      'adm_quick_actions': 'Швидкі дії',
      'adm_manage_users': 'Керування юзерами',
      'adm_moderate_jobs': 'Модерація вакансій',
      'adm_analytics': 'Аналітика',
      'adm_pending_approvals': 'Очікують схвалення',
      'adm_recent_activity': 'Остання активність',
      'adm_users': 'Користувачі',
      'adm_search_users': 'Пошук за ім\'ям або email...',
      'adm_candidates': 'Кандидати',
      'adm_employers': 'Роботодавці',
      'adm_admins': 'Адміни',
      'adm_active': 'Активний',
      'adm_pending': 'Очікує',
      'adm_banned': 'Заблокований',
      'adm_no_users': 'Користувачів не знайдено',
      'adm_registered': 'Реєстрація',
      'adm_last_login': 'Останній вхід',
      'adm_jobs_applied': 'Відгуків',
      'adm_approve': 'Схвалити',
      'adm_reject': 'Відхилити',
      'adm_message': 'Написати',
      'adm_ban': 'Заблокувати',
      'adm_unban': 'Розблокувати',
      'adm_job_moderation': 'Модерація вакансій',
      'adm_approved': 'Схвалена',
      'adm_rejected_status': 'Відхилена',
      'adm_featured': 'Просувана',
      'adm_security': 'Безпека',
      'adm_subscriptions': 'Підписки',
      'adm_subscribers': 'підписників',
      'all': 'Всі',
      'expired': 'Закінчився',
      'cancelled': 'Скасований',
      'change_plan': 'Змінити тариф',
      'extend': 'Продовжити',
      'extend_confirm': 'Продовжити підписку на:',
      'extended_by': 'продовжено на',
      'block': 'Заблокувати',
      'block_confirm': 'Заблокувати компанію? Підписку буде скасовано.',
      'blocked': 'заблоковано',
      'adm_approve_confirm': 'Користувач отримає повний доступ до платформи.',
      'adm_approved': 'схвалено',
      'adm_reject_reason': 'Вкажіть причину відхилення:',
      'adm_reason_hint': 'Введіть причину...',
      'adm_ban_confirm': 'Користувача буде заблоковано на платформі.',
      'adm_unban_confirm': 'Відновити доступ для цього користувача?',
      'adm_unbanned': 'розблоковано',
      'adm_approve_job_confirm': 'Вакансія буде видна всім кандидатам.',
      'adm_reject_job_reason': 'Причина відхилення вакансії:',
      'adm_feature_confirm': 'Показувати вакансію у топі пошуку?',
      'pending': 'Очікує',
      'resolved': 'Вирішено',
      'documents': 'Документи',
      'reason': 'Причина',
      'reported_by': 'Поскаржився',
      'adm_verify_approve': 'Верифікувати роботодавця? Він отримає значок верифікації.',
      'adm_take_action': 'Вжити заходів',
      'adm_warn_user': 'Надіслати попередження',
      'adm_warning_sent': 'Попередження надіслано',
      'adm_remove_content': 'Видалити контент',
      'adm_content_removed': 'Контент видалено',
      'adm_dismiss': 'Відхилити',
      'adm_report_dismissed': 'Скаргу відхилено',
      'adm_tools': 'ІНСТРУМЕНТИ АДМІНА',
      'adm_database': 'Система та база даних',
      'adm_verification': 'Верифікація',
      'adm_general': 'ЗАГАЛЬНЕ',
      'what_is_it': 'Що це?',
      'key_roles': 'Ключові ролі',
      'industry_stats': 'Статистика індустрії',
      'skills_needed': 'Потрібні навички',
      'want_to_learn': 'Хочете дізнатися більше?',
      'guro_school_desc': 'Почни кар\'єру в iGaming з професійними курсами Guro School',
      'go_to_guro_school': 'Guro School',
      'admin_panel': 'Панель адміна',
      'admin_login_desc': 'Увійдіть з обліковими даними адміністратора',
      'admin_only_error': 'Доступ заборонено. Тільки для адмінів.',
      'find_job_or_hire': 'Знайти роботу або найняти',
      'candidate_employer_desc': 'Для кандидатів і роботодавців',
      'choose_how_to_continue': 'Оберіть як продовжити',
      // Jarvis
      'jarvis': 'Джарвіс',
      'jarvis_hello': 'Привіт! Я Джарвіс, ваш AI-асистент.',
      'jarvis_hint': 'Спробуйте: "Статистика" або "Покажи вакансії"',
      'jarvis_ask': 'Запитайте Джарвіса...',
      'jarvis_listening': 'Слухаю...',
      'jarvis_processing': 'Обробка...',
      'jarvis_speaking': 'Говорю...',
      'jarvis_error': 'Помилка',
      'jarvis_connection_error': 'Помилка з\'єднання. Спробуйте ще раз.',
      // Filters
      'communication_preferences': 'Налаштування спілкування',
      'priority_language': 'Пріоритетна мова',
      'acceptable_languages': 'Прийнятні мови (1-3)',
      'select_language': 'Оберіть мову',
      'select_languages_hint': 'Натисніть для вибору мов',
      'candidate_filters': 'Країна та громадянство',
      'citizenship_country': 'Країна громадянства',
      'select_country': 'Оберіть країну',
      'in_citizenship_country': 'Ви знаходитесь у країні громадянства?',
      'blocked_company_countries': 'Відсікти країни компаній',
      'blocked_countries_hint': 'Країни, де не хочете працювати',
      'employer_filters': 'Налаштування кандидатів',
      'main_office_countries': 'Країна головного офісу',
      'select_countries': 'Оберіть країни',
      'blocked_candidate_citizenships': 'Відсікти громадянства кандидатів',
      'blocked_citizenships_hint': 'Громадянства, яким нічого запропонувати',
      'candidate_location_pref': 'Показати кандидатів',
      'all_candidates': 'Усі варіанти',
      'outside_citizenship': 'За межами країни',
      'save_changes': 'Зберегти',
      'profile_updated': 'Профіль оновлено!',
    },
  };

  static const Map<String, String> languageNames = {
    'en': 'English',
    'ru': 'Русский',
    'uk': 'Українська',
  };

  static const Map<String, String> languageFlags = {
    'en': '🇬🇧',
    'ru': '🇷🇺',
    'uk': '🇺🇦',
  };

  static String t(String key) {
    return _strings[_currentLang]?[key] ?? _strings['en']?[key] ?? key;
  }
}
