<?php

namespace App\Support;

class Countries
{
    public static function all(): array
    {
        return [
            ['code' => 'AL', 'name' => 'Albania'],
            ['code' => 'AD', 'name' => 'Andorra'],
            ['code' => 'AT', 'name' => 'Austria'],
            ['code' => 'BY', 'name' => 'Belarus'],
            ['code' => 'BE', 'name' => 'Belgium'],
            ['code' => 'BA', 'name' => 'Bosnia and Herzegovina'],
            ['code' => 'BG', 'name' => 'Bulgaria'],
            ['code' => 'HR', 'name' => 'Croatia'],
            ['code' => 'CY', 'name' => 'Cyprus'],
            ['code' => 'CZ', 'name' => 'Czech Republic'],
            ['code' => 'DK', 'name' => 'Denmark'],
            ['code' => 'EE', 'name' => 'Estonia'],
            ['code' => 'FI', 'name' => 'Finland'],
            ['code' => 'FR', 'name' => 'France'],
            ['code' => 'DE', 'name' => 'Germany'],
            ['code' => 'GR', 'name' => 'Greece'],
            ['code' => 'HU', 'name' => 'Hungary'],
            ['code' => 'IS', 'name' => 'Iceland'],
            ['code' => 'IE', 'name' => 'Ireland'],
            ['code' => 'IT', 'name' => 'Italy'],
            ['code' => 'XK', 'name' => 'Kosovo'],
            ['code' => 'LV', 'name' => 'Latvia'],
            ['code' => 'LI', 'name' => 'Liechtenstein'],
            ['code' => 'LT', 'name' => 'Lithuania'],
            ['code' => 'LU', 'name' => 'Luxembourg'],
            ['code' => 'MT', 'name' => 'Malta'],
            ['code' => 'MD', 'name' => 'Moldova'],
            ['code' => 'MC', 'name' => 'Monaco'],
            ['code' => 'ME', 'name' => 'Montenegro'],
            ['code' => 'NL', 'name' => 'Netherlands'],
            ['code' => 'MK', 'name' => 'North Macedonia'],
            ['code' => 'NO', 'name' => 'Norway'],
            ['code' => 'PL', 'name' => 'Poland'],
            ['code' => 'PT', 'name' => 'Portugal'],
            ['code' => 'RO', 'name' => 'Romania'],
            ['code' => 'RU', 'name' => 'Russia'],
            ['code' => 'SM', 'name' => 'San Marino'],
            ['code' => 'RS', 'name' => 'Serbia'],
            ['code' => 'SK', 'name' => 'Slovakia'],
            ['code' => 'SI', 'name' => 'Slovenia'],
            ['code' => 'ES', 'name' => 'Spain'],
            ['code' => 'SE', 'name' => 'Sweden'],
            ['code' => 'CH', 'name' => 'Switzerland'],
            ['code' => 'TR', 'name' => 'Turkey'],
            ['code' => 'UA', 'name' => 'Ukraine'],
            ['code' => 'GB', 'name' => 'United Kingdom'],
            ['code' => 'VA', 'name' => 'Vatican City'],
            // Non-European (popular for iGaming)
            ['code' => 'GI', 'name' => 'Gibraltar'],
            ['code' => 'IM', 'name' => 'Isle of Man'],
            ['code' => 'JE', 'name' => 'Jersey'],
            ['code' => 'GG', 'name' => 'Guernsey'],
            ['code' => 'CW', 'name' => 'Curaçao'],
            ['code' => 'PH', 'name' => 'Philippines'],
            ['code' => 'IN', 'name' => 'India'],
            ['code' => 'BR', 'name' => 'Brazil'],
            ['code' => 'US', 'name' => 'United States'],
            ['code' => 'CA', 'name' => 'Canada'],
            ['code' => 'AU', 'name' => 'Australia'],
            ['code' => 'NZ', 'name' => 'New Zealand'],
            ['code' => 'ZA', 'name' => 'South Africa'],
            ['code' => 'IL', 'name' => 'Israel'],
            ['code' => 'AE', 'name' => 'United Arab Emirates'],
            ['code' => 'SG', 'name' => 'Singapore'],
            ['code' => 'JP', 'name' => 'Japan'],
            ['code' => 'KR', 'name' => 'South Korea'],
            ['code' => 'CN', 'name' => 'China'],
            ['code' => 'GE', 'name' => 'Georgia'],
            ['code' => 'AM', 'name' => 'Armenia'],
            ['code' => 'AZ', 'name' => 'Azerbaijan'],
            ['code' => 'KZ', 'name' => 'Kazakhstan'],
            ['code' => 'UZ', 'name' => 'Uzbekistan'],
            ['code' => 'KG', 'name' => 'Kyrgyzstan'],
            ['code' => 'TJ', 'name' => 'Tajikistan'],
            ['code' => 'MX', 'name' => 'Mexico'],
            ['code' => 'AR', 'name' => 'Argentina'],
            ['code' => 'CO', 'name' => 'Colombia'],
            ['code' => 'CL', 'name' => 'Chile'],
            ['code' => 'PE', 'name' => 'Peru'],
            ['code' => 'NG', 'name' => 'Nigeria'],
            ['code' => 'KE', 'name' => 'Kenya'],
            ['code' => 'TH', 'name' => 'Thailand'],
            ['code' => 'VN', 'name' => 'Vietnam'],
            ['code' => 'MY', 'name' => 'Malaysia'],
            ['code' => 'ID', 'name' => 'Indonesia'],
        ];
    }

    public static function languages(): array
    {
        return [
            ['code' => 'en', 'name' => 'English'],
            ['code' => 'de', 'name' => 'German'],
            ['code' => 'pl', 'name' => 'Polish'],
            ['code' => 'ru', 'name' => 'Russian'],
            ['code' => 'uk', 'name' => 'Ukrainian'],
            ['code' => 'fr', 'name' => 'French'],
            ['code' => 'es', 'name' => 'Spanish'],
            ['code' => 'pt', 'name' => 'Portuguese'],
            ['code' => 'it', 'name' => 'Italian'],
            ['code' => 'nl', 'name' => 'Dutch'],
            ['code' => 'sv', 'name' => 'Swedish'],
            ['code' => 'da', 'name' => 'Danish'],
            ['code' => 'no', 'name' => 'Norwegian'],
            ['code' => 'fi', 'name' => 'Finnish'],
            ['code' => 'el', 'name' => 'Greek'],
            ['code' => 'cs', 'name' => 'Czech'],
            ['code' => 'ro', 'name' => 'Romanian'],
            ['code' => 'bg', 'name' => 'Bulgarian'],
            ['code' => 'hr', 'name' => 'Croatian'],
            ['code' => 'sr', 'name' => 'Serbian'],
            ['code' => 'sk', 'name' => 'Slovak'],
            ['code' => 'hu', 'name' => 'Hungarian'],
            ['code' => 'tr', 'name' => 'Turkish'],
            ['code' => 'ja', 'name' => 'Japanese'],
            ['code' => 'ko', 'name' => 'Korean'],
            ['code' => 'zh', 'name' => 'Chinese'],
            ['code' => 'ar', 'name' => 'Arabic'],
            ['code' => 'hi', 'name' => 'Hindi'],
            ['code' => 'th', 'name' => 'Thai'],
            ['code' => 'vi', 'name' => 'Vietnamese'],
            ['code' => 'he', 'name' => 'Hebrew'],
            ['code' => 'ka', 'name' => 'Georgian'],
        ];
    }
}
